// Generated by GitHub Copilot - Sep-30-2026
import { test, expect } from '@playwright/test';

test('Three.js actually renders changing frames and the pause control stops ambient motion', async ({ page }) => {
  await page.addInitScript(() => {
    const original = WebGL2RenderingContext.prototype.drawElements;
    WebGL2RenderingContext.prototype.drawElements = function (...args) {
      const count = Number(document.documentElement.dataset.drawCalls ?? '0');
      document.documentElement.dataset.drawCalls = String(count + 1);
      return original.apply(this, args);
    };
  });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto('/');
  const scene = page.locator('.engineering-scene');
  await expect(scene).toHaveAttribute('data-renderer', 'webgl', { timeout: 25000 });
  await page.evaluate(() => document.fonts.ready);
  const canvas = scene.locator('canvas');
  const first = (await canvas.screenshot()).toString('base64');
  await expect.poll(async () => (await canvas.screenshot()).toString('base64'), { timeout: 10000, intervals: [300, 500] }).not.toBe(first);
  await page.getByRole('button', { name: 'Pause ambient animations' }).click();
  await expect(page.locator('.portfolio-shell')).toHaveAttribute('data-motion', 'paused');
  expect(await page.locator('.ribbon-track').evaluate(el => getComputedStyle(el).animationPlayState)).toBe('paused');
  const before = await page.locator('html').getAttribute('data-draw-calls');
  // Wait for browser frames, not pixel screenshots that also include unrelated DOM overlays.
  await page.evaluate(() => new Promise<void>(resolve => {
    let frames = 0;
    const next = () => { frames += 1; if (frames === 20) { resolve(); } else { requestAnimationFrame(next); } };
    requestAnimationFrame(next);
  }));
  expect(await page.locator('html').getAttribute('data-draw-calls')).toBe(before);
  await page.getByRole('button', { name: 'Play ambient animations' }).click();
  await expect(page.locator('.portfolio-shell')).toHaveAttribute('data-motion', 'playing');
  await page.locator('#contact').scrollIntoViewIfNeeded();
  await expect(page.locator('.portrait-stage')).toHaveAttribute('data-visible', 'false');
});

test('reduced motion uses a static orbit without loading a WebGL canvas', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await expect(page.locator('.engineering-scene')).toHaveAttribute('data-renderer', 'fallback');
  await expect(page.locator('.engineering-scene canvas')).toHaveCount(0);
  await expect(page.locator('.motion-toggle')).toBeDisabled();
  expect(await page.locator('.floating-tag').first().evaluate(el => getComputedStyle(el).animationName)).toBe('none');
});

test('losing WebGL leaves an accessible static fallback rather than a broken hero', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto('/');
  const scene = page.locator('.engineering-scene');
  await expect(scene).toHaveAttribute('data-renderer', 'webgl', { timeout: 25000 });
  await scene.locator('canvas').evaluate(el => {
    el.dispatchEvent(new Event('webglcontextlost', { cancelable: true }));
  });
  await expect(scene).toHaveAttribute('data-renderer', 'fallback');
  await expect(scene.locator('canvas')).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Explore my work' })).toBeVisible();
});