// Generated by GitHub Copilot - Sep-30-2026
import test from 'node:test';
import assert from 'node:assert/strict';
import { createContactHandler, validateMessage } from '../api/contact.mjs';
import { recruiterEmail } from '../server/email-template.mjs';

const env = { CONTACT_ORIGIN: 'https://portfolio.test', CONTACT_FROM: 'portfolio@sender.test', RESEND_API_KEY: 'test-only', TURNSTILE_SECRET_KEY: 'test-secret', TURNSTILE_SITE_KEY: 'public-test-key' };
const valid = { name: 'Recruiter', email: 'recruiter@example.test', company: 'Hiring team', message: 'Please contact me about an engineering opportunity.', token: 'test-token', requestId: '5c9c1434-b082-4bf8-a145-37aa8adf6307', website: '', consent: true };

/** Captures HTTP output without making any external requests or sending mail. */
async function invoke({ method = 'POST', body = valid, headers = {}, settings = env, fetcher = async () => { throw new Error('Unexpected external request'); } } = {}) {
  const response = { code: 200, headers: {}, value: null, setHeader(key, value) { this.headers[key] = value; }, status(code) { this.code = code; return this; }, json(value) { this.value = value; return this; } };
  await createContactHandler({ env: settings, fetcher })({ method, body, headers: { origin: env.CONTACT_ORIGIN, 'content-type': 'application/json', ...headers } }, response);
  return response;
}

test('contact config exposes only public verification settings, never secrets', async () => {
  const result = await invoke({ method: 'GET' });
  assert.deepEqual(result.value, { available: true, siteKey: 'public-test-key' });
  assert.equal(result.headers['Cache-Control'], 'no-store');
  assert.doesNotMatch(JSON.stringify(result.value), /test-secret|test-only|sender\.test/);
});
test('missing or invalid contact configuration fails closed', async () => {
  assert.deepEqual((await invoke({ method: 'GET', settings: {} })).value, { available: false, siteKey: '' });
  assert.equal((await invoke({ settings: {} })).code, 503);
  assert.equal((await invoke({ settings: { ...env, CONTACT_ORIGIN: 'http://portfolio.test' } })).code, 503);
  assert.equal((await invoke({ settings: { ...env, CONTACT_FROM: 'injected\r\n@sender.test' } })).code, 503);
});
test('contact rejects wrong methods, cross-origin requests, and unexpected content types', async () => {
  assert.equal((await invoke({ method: 'DELETE' })).code, 405);
  assert.equal((await invoke({ headers: { origin: 'https://untrusted.test' } })).code, 403);
  assert.equal((await invoke({ headers: { 'content-type': 'text/plain' } })).code, 415);
});
test('contact validates size, consent, header injection, email and honeypot', async () => {
  for (const patch of [{ consent: false }, { name: '' }, { name: 'Name\r\nBcc: other@example.test' }, { email: 'not-email' }, { website: 'spam' }, { message: 'short' }, { message: 'a'.repeat(4001) }, { token: '' }, { requestId: 'bad' }]) assert.equal(validateMessage({ ...valid, ...patch }), null);
  assert.equal((await invoke({ body: 'invalid json' })).code, 400);
  assert.equal((await invoke({ body: 'x'.repeat(16001) })).code, 413);
  assert.equal((await invoke({ headers: { 'content-length': '16001' } })).code, 413);
});
test('email HTML escapes visitor content and includes a plain text version', () => {
  const result = recruiterEmail({ ...valid, name: '<img src=x>', company: '<script>bad</script>', message: 'Hello <script>alert(1)</script> & goodbye' });
  assert.doesNotMatch(result.html, /<script>|<img/);
  assert.match(result.html, /&lt;script&gt;/);
  assert.match(result.html, /&amp; goodbye/);
  assert.match(result.text, /Hello <script>/);
});
test('bot verification must succeed for the allowed hostname and contact action', async () => {
  for (const verification of [{ success: false }, { success: true, hostname: 'other.test', action: 'contact' }, { success: true, hostname: 'portfolio.test', action: 'other' }]) {
    let calls = 0;
    const result = await invoke({ fetcher: async () => { calls++; return Response.json(verification); } });
    assert.equal(result.code, 400); assert.equal(calls, 1);
  }
});
test('accepted contact uses fixed inbox, reply-to, template and idempotency key', async () => {
  const requests = [];
  const result = await invoke({ body: { ...valid, to: 'attacker@example.test' }, fetcher: async (url, options) => {
    requests.push({ url, options });
    return url.includes('siteverify') ? Response.json({ success: true, hostname: 'portfolio.test', action: 'contact' }) : Response.json({ id: 'provider-accepted-id' });
  } });
  assert.equal(result.code, 202); assert.deepEqual(result.value, { accepted: true });
  assert.equal(requests.length, 2);
  const email = JSON.parse(requests[1].options.body);
  assert.deepEqual(email.to, ['shilpakalwar25@gmail.com']);
  assert.equal(email.reply_to, valid.email);
  assert.match(email.html, /A new conversation/);
  assert.match(requests[1].options.headers['Idempotency-Key'], /^[a-f0-9]{64}$/);
});
test('provider failures and timeouts never report a sent message', async () => {
  for (const status of [429, 500]) {
    const result = await invoke({ fetcher: async url => url.includes('siteverify') ? Response.json({ success: true, hostname: 'portfolio.test', action: 'contact' }) : Response.json({ error: 'private provider detail' }, { status }) });
    assert.equal(result.code, status === 429 ? 429 : 502);
    assert.doesNotMatch(JSON.stringify(result.value), /private provider detail|accepted/);
  }
  assert.equal((await invoke({ fetcher: async () => { throw new Error('timeout'); } })).code, 502);
});