// Generated by GitHub Copilot - Sep-30-2026
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createMediaManifest } from '../scripts/media-manifest.mjs';

test('missing uploads never produce broken image or resume links', () => {
  const media = createMediaManifest(join(tmpdir(), 'portfolio-nonexistent-media'));
  assert.deepEqual(media, { portrait: null, resume: null, studymate: [], pizzeria: [] });
});

test('only recognized originals are mapped with meaningful screenshot descriptions', () => {
  const directory = mkdtempSync(join(tmpdir(), 'portfolio-media-'));
  try {
    for (const name of ['portrait.JPG', 'studymate-qa.png', 'studymate-home.webp', 'pizzeria-assistant.jpg', 'pizzeria-meal.png', 'resume.pdf', 'unrelated.png']) {
      writeFileSync(join(directory, name), 'test fixture; not a production image');
    }
    const media = createMediaManifest(directory);
    assert.equal(media.portrait, '/uploads/portrait.JPG');
    assert.equal(media.resume, '/uploads/resume.pdf');
    assert.equal(media.studymate.length, 2);
    assert.equal(media.pizzeria.length, 2);
    assert.equal(media.studymate[0].src, '/uploads/studymate-home.webp');
    assert.ok(media.studymate.every(image => image.alt.length > 30 && image.caption.length > 30));
    assert.ok(!JSON.stringify(media).includes('unrelated'));
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});