// Generated by GitHub Copilot - Sep-30-2026
import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

/** Mocks verification and delivery so the test suite never sends email or contacts a real CAPTCHA service. */
async function mockDelivery(page: Page, status = 202) {
  await page.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit', route => route.fulfill({ contentType: 'application/javascript', body: 'window.turnstile = { render: function(el, opts) { opts.callback("verified-test-token"); return "test-widget"; }, remove: function() {} };' }));
  await page.route('**/api/contact', route => route.request().method() === 'GET'
    ? route.fulfill({ json: { available: true, siteKey: 'test-key' } })
    : route.fulfill({ status, json: status === 202 ? { accepted: true } : { error: 'Email service unavailable. Please try later.' } }));
}

/** Completes the labelled recruiter fields with synthetic data. */
async function fillMessage(page: Page) {
  await page.getByRole('button', { name: 'Talk to me', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Talk to Shilpa' });
  await dialog.getByLabel('Your name', { exact: true }).fill('Example Recruiter');
  await dialog.getByLabel('Your email', { exact: true }).fill('recruiter@example.test');
  await dialog.getByLabel('Your message', { exact: true }).fill('I would like to discuss an engineering opportunity.');
  await dialog.getByRole('checkbox').check();
  return dialog;
}

test('requested sections are in order and removed marketing panels stay removed', async ({ page }) => {
  await page.goto('/');
  const ids = await page.locator('main > section[id]').evaluateAll(elements => elements.map(element => element.id));
  expect(ids).toEqual(['home', 'about', 'experience', 'projects', 'skills', 'education', 'achievements', 'contact']);
  await expect(page.locator('#education #certifications')).toHaveCount(1);
  await expect(page.locator('.impact-strip,.about-principles,.coverage-section,.news-story')).toHaveCount(0);
  await expect(page.locator('body')).not.toContainText('Gemini');
  await expect(page.locator('#home')).not.toContainText(/AI-powered|Practical AI/);
  await expect(page.locator('#skills .skill-chip').filter({ hasText: /^C#$/ })).toHaveCount(1);
  await expect(page.locator('#skills .skill-chip').filter({ hasText: /^\.NET$/ })).toHaveCount(1);
});

test('unconfigured contact is honest, accessible, and restores keyboard focus', async ({ page }) => {
  await page.route('**/api/contact', route => route.fulfill({ json: { available: false, siteKey: '' } }));
  await page.goto('/');
  const dialog = await fillMessage(page);
  await expect(dialog.getByRole('button', { name: 'Send message' })).toBeDisabled();
  await expect(dialog.getByRole('status')).toContainText('Direct sending is not configured');
  await expect(dialog.getByRole('link', { name: 'Open email app instead' })).toHaveAttribute('href', /mailto:shilpakalwar25@gmail.com\?subject=/);
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(audit.violations).toEqual([]);
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Talk to me', exact: true })).toBeFocused();
});

test('contact validates fields and acknowledges only confirmed provider acceptance', async ({ page }) => {
  await mockDelivery(page);
  await page.goto('/');
  const dialog = await fillMessage(page);
  await dialog.getByLabel('Your email', { exact: true }).fill('bad-email');
  await dialog.getByRole('button', { name: 'Send message' }).click();
  expect(await dialog.getByLabel('Your email', { exact: true }).evaluate(element => (element as HTMLInputElement).validity.valid)).toBe(false);
  await dialog.getByLabel('Your email', { exact: true }).fill('recruiter@example.test');
  const outgoing = page.waitForRequest(request => request.url().endsWith('/api/contact') && request.method() === 'POST');
  await dialog.getByRole('button', { name: 'Send message' }).click();
  expect((await outgoing).postDataJSON()).toMatchObject({ consent: true, email: 'recruiter@example.test', token: 'verified-test-token' });
  await expect(dialog.getByRole('status')).toContainText('Message accepted for delivery');
});

test('contact retains message and shows service errors without claiming success', async ({ page }) => {
  await mockDelivery(page, 502);
  await page.goto('/');
  const dialog = await fillMessage(page);
  await dialog.getByRole('button', { name: 'Send message' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Email service unavailable');
  await expect(dialog.getByLabel('Your message', { exact: true })).toHaveValue(/engineering opportunity/);
  await expect(dialog.getByText('Message accepted for delivery', { exact: true })).toHaveCount(0);
});

test('contact dialog fits narrow mobile and contains keyboard focus', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 });
  await page.route('**/api/contact', route => route.fulfill({ json: { available: false, siteKey: '' } }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Talk to me', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByLabel('Your name', { exact: true })).toBeFocused();
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  for (let index = 0; index < 14; index++) {
    await page.keyboard.press('Tab');
    expect(await page.evaluate(() => !!document.activeElement?.closest('dialog'))).toBe(true);
  }
});

test('new motion is active when enabled and all CSS loops pause on request', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.goto('/');
  await expect(page.locator('.portfolio-shell')).toHaveAttribute('data-motion', 'playing');
  const emphasis = page.locator('.hero-emphasis');
  expect(await emphasis.evaluate(element => getComputedStyle(element).animationName)).toBe('word-light');
  await page.getByRole('button', { name: 'Pause ambient animations' }).click();
  expect(await emphasis.evaluate(element => getComputedStyle(element).animationPlayState)).toBe('paused');
  await page.locator('#contact').scrollIntoViewIfNeeded();
  expect(await page.locator('.message-trigger').evaluate(element => getComputedStyle(element).animationPlayState)).toBe('paused');
});