// Generated by GitHub Copilot - Sep-30-2026
import { useContext, useEffect, useRef } from 'react';
import { useReducedMotion } from 'motion/react';
import { MotionPausedContext } from './EngineeringVisuals';

interface Bubble {
  x: number;
  y: number;
  vx: number;
  vy: number;
  radius: number;
  hue: number;
  alpha: number;
  drift: number;
  phase: number;
}

/**
 * Paints a low-cost animated bubble field that drifts across the viewport and
 * gently reacts to the pointer. Renders nothing when motion is paused, when
 * the tab is hidden, or when the user prefers reduced motion. All GPU
 * resources are released on unmount so no background loop persists.
 */
export default function AmbientBubbles() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const paused = useContext(MotionPausedContext);
  const reduced = useReducedMotion();
  const active = !paused && !reduced;

  useEffect(() => {
    if (!active) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const context = canvas.getContext('2d', { alpha: true });
    if (!context) return;

    const state = {
      width: 0,
      height: 0,
      dpr: Math.min(window.devicePixelRatio || 1, 2),
      bubbles: [] as Bubble[],
      pointerX: -9999,
      pointerY: -9999,
      pointerActive: false,
      lastTime: performance.now(),
      running: true,
    };

    /** Sizes the canvas to the viewport and rescales the drawing context. */
    const resize = () => {
      const { innerWidth, innerHeight } = window;
      state.width = innerWidth;
      state.height = innerHeight;
      state.dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.floor(innerWidth * state.dpr);
      canvas.height = Math.floor(innerHeight * state.dpr);
      canvas.style.width = `${innerWidth}px`;
      canvas.style.height = `${innerHeight}px`;
      context.setTransform(state.dpr, 0, 0, state.dpr, 0, 0);
      seed();
    };

    /** Populates the field with a device-appropriate number of bubbles. */
    const seed = () => {
      const area = state.width * state.height;
      const target = Math.max(28, Math.min(75, Math.round(area / 28000)));
      state.bubbles = Array.from({ length: target }, () => createBubble(true));
    };

    /**
     * Non-cryptographic pseudo-random helper for cosmetic animation values only.
     * Math.random is safe here because bubble positions and colors never gate
     * security, authentication, or data integrity decisions.
     */
    const rand = () => Math.random();

    /** Creates a single bubble, optionally scattered across the whole viewport. */
    const createBubble = (scatter: boolean): Bubble => {
      const radius = 18 + rand() * 75;
      return {
        x: rand() * state.width,
        y: scatter ? rand() * state.height : state.height + radius + rand() * 120,
        vx: (rand() - .5) * .18,
        vy: -(.12 + rand() * .32),
        radius,
        hue: 265 + rand() * 55,
        alpha: .09 + rand() * .18,
        drift: .4 + rand() * .8,
        phase: rand() * Math.PI * 2,
      };
    };

    /** Advances every bubble and paints the current frame. */
    const step = (now: number) => {
      if (!state.running) return;
      const delta = Math.min(48, now - state.lastTime);
      state.lastTime = now;

      context.clearRect(0, 0, state.width, state.height);
      context.globalCompositeOperation = 'lighter';

      for (const bubble of state.bubbles) {
        bubble.phase += delta * .001 * bubble.drift;
        bubble.x += bubble.vx * delta + Math.sin(bubble.phase) * .15;
        bubble.y += bubble.vy * delta;

        if (state.pointerActive) {
          const dx = bubble.x - state.pointerX;
          const dy = bubble.y - state.pointerY;
          const distance = Math.hypot(dx, dy);
          const influence = 170;
          if (distance < influence && distance > 0.01) {
            const force = (1 - distance / influence) * .55;
            bubble.x += (dx / distance) * force * delta * .18;
            bubble.y += (dy / distance) * force * delta * .18;
          }
        }

        if (bubble.y + bubble.radius < -40 || bubble.x < -80 || bubble.x > state.width + 80) {
          Object.assign(bubble, createBubble(false));
        }

        const gradient = context.createRadialGradient(
          bubble.x,
          bubble.y,
          bubble.radius * .2,
          bubble.x,
          bubble.y,
          bubble.radius,
        );
        const core = `hsla(${bubble.hue}, 95%, 78%, ${bubble.alpha})`;
        const edge = `hsla(${bubble.hue}, 92%, 60%, 0)`;
        gradient.addColorStop(0, core);
        gradient.addColorStop(1, edge);
        context.fillStyle = gradient;
        context.beginPath();
        context.arc(bubble.x, bubble.y, bubble.radius, 0, Math.PI * 2);
        context.fill();
      }

      if (state.pointerActive) {
        const cursor = context.createRadialGradient(
          state.pointerX,
          state.pointerY,
          0,
          state.pointerX,
          state.pointerY,
          140,
        );
        cursor.addColorStop(0, 'hsla(292, 96%, 74%, .18)');
        cursor.addColorStop(1, 'hsla(292, 96%, 60%, 0)');
        context.fillStyle = cursor;
        context.beginPath();
        context.arc(state.pointerX, state.pointerY, 140, 0, Math.PI * 2);
        context.fill();
      }

      frame = requestAnimationFrame(step);
    };

    /** Tracks pointer position for the interactive glow and repulsion. */
    const onPointerMove = (event: PointerEvent) => {
      if (event.pointerType && event.pointerType !== 'mouse' && event.pointerType !== 'pen') return;
      state.pointerX = event.clientX;
      state.pointerY = event.clientY;
      state.pointerActive = true;
    };

    /** Clears pointer influence when it leaves the viewport. */
    const onPointerLeave = () => {
      state.pointerActive = false;
      state.pointerX = -9999;
      state.pointerY = -9999;
    };

    let frame = 0;
    resize();
    frame = requestAnimationFrame(step);
    window.addEventListener('resize', resize);
    window.addEventListener('pointermove', onPointerMove, { passive: true });
    document.documentElement.addEventListener('pointerleave', onPointerLeave);

    return () => {
      state.running = false;
      cancelAnimationFrame(frame);
      window.removeEventListener('resize', resize);
      window.removeEventListener('pointermove', onPointerMove);
      document.documentElement.removeEventListener('pointerleave', onPointerLeave);
      context.clearRect(0, 0, state.width, state.height);
    };
  }, [active]);

  return <canvas ref={canvasRef} className="ambient-bubbles" data-active={active} />;
}
