// Generated by GitHub Copilot - Sep-30-2026
import { useEffect, useRef, useState } from 'react';
import { motion } from 'motion/react';
import {
  ArrowRight,
  ArrowUpRight,
  Check,
  ChevronLeft,
  ChevronRight,
  GitFork as Github,
  X,
} from 'lucide-react';
import type { Project } from '../data';
import { ProjectVisual } from './Visuals';
import { AnimatedFlow, useQuietMotion } from './EngineeringVisuals';

// Generated by GitHub Copilot - Sep-30-2026
/** Selects the existing architecture heading, preserving the discovery fallback. */
function getArchitectureHeading(projectId: Project['id']): string {
  switch (projectId) {
    case 'pizzeria':
      return 'Turning language into a validated action.';
    case 'studymate':
      return 'From a document to a learning loop.';
    default:
      return 'From scattered sources to focused discovery.';
  }
}

/** Uses native modal focus management and restores the opener after the closing animation. */
export default function CaseStudy({ project, onClose }: Readonly<{
  project: Project;
  onClose: () => void;
}>) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [closing, setClosing] = useState(false);
  const [imageIndex, setImageIndex] = useState(0);
  const reduced = useQuietMotion();
  /** Starts the exit animation without closing the native dialog early. */
  const close = () => setClosing(true);
  useEffect(() => {
    const element = dialog.current;
    const opener = document.activeElement as HTMLElement | null;
    const oldOverflow = document.body.style.overflow;
    const oldTitle = document.title;
    document.title = `${project.name} — Engineering Case Study | Shilpa Gupta`;
    element?.showModal();
    document.body.style.overflow = 'hidden';
    return () => {
      element?.close();
      document.body.style.overflow = oldOverflow;
      document.title = oldTitle;
      opener?.focus({ preventScroll: true });
    };
  }, [project.name]);
  const screenshot = project.screenshots[imageIndex];
  return (
    <dialog
      ref={dialog}
      className={`case-dialog case-${project.id}`}
      aria-labelledby="case-title"
      onCancel={e => {
        e.preventDefault();
        close();
      }}
      onClick={e => {
        if (e.target === e.currentTarget) {
          const rect = e.currentTarget.getBoundingClientRect();
          if (
            e.clientX < rect.left
            || e.clientX > rect.right
            || e.clientY < rect.top
            || e.clientY > rect.bottom
          ) {
            close();
          }
        }
      }}
    >
      <motion.div
        className="case-panel"
        initial={{ opacity: 0, y: reduced ? 0 : 24 }}
        animate={{ opacity: closing ? 0 : 1, y: closing && !reduced ? 16 : 0 }}
        transition={{ duration: reduced ? 0 : .25 }}
        onAnimationComplete={() => {
          if (closing) {
            onClose();
          }
        }}
      >
        <div className="case-toolbar">
          <span>SELECTED WORK <span>/ {project.number}</span></span>
          <button autoFocus className="case-close" onClick={close}>
            Close case study <X size={18} />
          </button>
        </div>
        <div className="case-body">
          <div className="case-heading">
            <p className="eyebrow">{project.category}</p>
            <h2 id="case-title">{project.name}</h2>
            <p className="case-tagline">{project.tagline}</p>
            <div className="chip-list">
              {project.stack.map(t => <span className="chip" key={t}>{t}</span>)}
            </div>
            <div className="case-links">
              {project.live && (
                <a className="button button-primary" href={project.live} target="_blank" rel="noreferrer">
                  Explore live project <ArrowUpRight size={17} />
                </a>
              )}
              {project.github && (
                <a className="button button-secondary" href={project.github} target="_blank" rel="noreferrer">
                  <Github size={16} />Source code
                </a>
              )}
              <span className="case-label">ENGINEERING CASE STUDY</span>
            </div>
          </div>
          <div className="case-preview">
            {screenshot ? (
              <div className="screenshot-gallery">
                <figure>
                  <img src={screenshot.src} alt={screenshot.alt} decoding="async" />
                  <figcaption>{screenshot.caption}</figcaption>
                </figure>
                {project.screenshots.length > 1 && (
                  <div className="gallery-thumbnails" aria-label={`${project.name} screenshot selection`}>
                    {project.screenshots.map((image, index) => (
                      <button className="gallery-thumbnail" key={image.src} aria-label={`View screenshot ${index + 1}: ${image.caption}`} aria-pressed={imageIndex === index} onClick={() => setImageIndex(index)}>
                        <img src={image.src} alt="" loading="lazy" decoding="async" />
                      </button>
                    ))}
                  </div>
                )}
                {project.screenshots.length > 1 && (
                  <div className="gallery-controls">
                    <button
                      className="icon-button"
                      aria-label="Previous screenshot"
                      onClick={() => setImageIndex(
                        (imageIndex + project.screenshots.length - 1) % project.screenshots.length
                      )}
                    >
                      <ChevronLeft />
                    </button>
                    <span aria-live="polite">{imageIndex + 1} / {project.screenshots.length}</span>
                    <button
                      className="icon-button"
                      aria-label="Next screenshot"
                      onClick={() => setImageIndex((imageIndex + 1) % project.screenshots.length)}
                    >
                      <ChevronRight />
                    </button>
                  </div>
                )}
              </div>
            ) : <ProjectVisual project={project} interactive />}
          </div>
          <section className="case-section" aria-labelledby="case-overview">
            <span className="case-section-index">01 / CONTEXT</span>
            <h3 id="case-overview">The idea behind the interface.</h3>
            <p className="case-lead">{project.description}</p>
            <div className="problem-solution">
              <div>
                <h4>The problem</h4>
                <p>{project.problem}</p>
              </div>
              <div>
                <h4>The solution</h4>
                <p>{project.solution}</p>
              </div>
            </div>
          </section>
          <section className="case-section" aria-labelledby="case-features">
            <span className="case-section-index">02 / CAPABILITIES</span>
            <h3 id="case-features">What the product brings together.</h3>
            <ul className="case-features">
              {project.features.map(feature => <li key={feature}><Check size={17} />{feature}</li>)}
            </ul>
          </section>
          <section className="case-section case-architecture" aria-labelledby="case-architecture">
            <span className="case-section-index">03 / UNDER THE HOOD</span>
            <h3 id="case-architecture">{getArchitectureHeading(project.id)}</h3>
            <p>{project.architecture}</p>
            {project.flows.map(flow => <AnimatedFlow key={flow.title} flow={flow} />)}
          </section>
          <section className="case-section" aria-labelledby="case-decisions">
            <span className="case-section-index">04 / ENGINEERING DECISIONS</span>
            <h3 id="case-decisions">The work beyond the happy path.</h3>
            <div className="challenge-list">
              {project.challenges.map((challenge, i) => (
                <div className="challenge" key={challenge.title}>
                  <span>0{i + 1}</span>
                  <div>
                    <h4>{challenge.title}</h4>
                    <p>{challenge.body}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
          <section className="case-section" aria-labelledby="case-implementation">
            <span className="case-section-index">05 / IMPLEMENTATION</span>
            <h3 id="case-implementation">Connecting the pieces.</h3>
            <ol className="implementation-list">
              {project.implementation.map(step => <li key={step}>{step}</li>)}
            </ol>
            <div className="optimization-note">
              <h4>Performance & reliability considerations</h4>
              <p>{project.optimization}</p>
            </div>
          </section>
          <section className="case-section case-deployment" aria-labelledby="case-deployment">
            <span className="case-section-index">06 / DEPLOYMENT</span>
            <h3 id="case-deployment">{project.live ? 'Take a closer look.' : 'A project in focus.'}</h3>
            <p>{project.deployment}</p>
            <div className="case-links">
              {project.live && (
                <a className="button button-primary" href={project.live} target="_blank" rel="noreferrer">
                  Visit {project.name}<ArrowUpRight size={16} />
                </a>
              )}
              <button className="text-link" onClick={close}>
                Back to selected work <ArrowRight size={17} />
              </button>
            </div>
          </section>
        </div>
      </motion.div>
    </dialog>
  );
}