// Generated by GitHub Copilot - Sep-30-2026
import { useEffect, useRef, useState, type SyntheticEvent, type KeyboardEvent } from 'react';
import { motion } from 'motion/react';
import { Check, Mail, MessageCircle, Send, X } from 'lucide-react';
import { useQuietMotion } from './EngineeringVisuals';

type TurnstileApi = {
  render: (element: HTMLElement, options: { sitekey: string; action: string; theme: string; size: string; callback: (token: string) => void; 'expired-callback': () => void; 'error-callback': () => void }) => string;
  remove: (id: string) => void;
};
declare global { interface Window { turnstile?: TurnstileApi } }
let scriptLoading: Promise<void> | undefined;

/** Loads verification only after opening the form; no private email credentials reach the client. */
function loadVerification() {
  if (window.turnstile) return Promise.resolve();
  if (!scriptLoading) {
    scriptLoading = new Promise<void>((resolve, reject) => {
      const script = document.createElement('script');
      script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';
      script.async = true;
      script.onload = () => resolve();
      script.onerror = () => { script.remove(); scriptLoading = undefined; reject(new Error('Verification could not load')); };
      document.head.append(script);
    });
  }
  return scriptLoading;
}

/** Renders a disposable accessible verification widget and invalidates expired tokens. */
function Verification({ siteKey, onToken, onError }: Readonly<{ siteKey: string; onToken: (value: string) => void; onError: (value: string) => void }>) {
  const host = useRef<HTMLDivElement>(null);
  useEffect(() => {
    let disposed = false;
    let widget: string | undefined;
    loadVerification().then(() => {
      if (disposed || !host.current || !window.turnstile) return;
      widget = window.turnstile.render(host.current, {
        sitekey: siteKey, action: 'contact', theme: 'dark', size: 'flexible', callback: onToken,
        'expired-callback': () => onToken(''),
        'error-callback': () => { onToken(''); onError('Verification could not load. Please use the email link or reopen this dialog.'); },
      });
    }).catch(() => { if (!disposed) onError('Verification could not load. Please use the email link.'); });
    return () => { disposed = true; if (widget) window.turnstile?.remove(widget); };
  }, [siteKey, onToken, onError]);
  return <div className="contact-verification" ref={host} />;
}

/** Presents a native modal message composer; success requires server/provider acknowledgement. */
export default function ContactDialog({ onClose }: Readonly<{ onClose: () => void }>) {
  const dialog = useRef<HTMLDialogElement>(null);
  const request = useRef<AbortController | null>(null);
  const requestId = useRef(crypto.randomUUID());
  const [config, setConfig] = useState<{ available: boolean; siteKey: string } | null>(null);
  const [fields, setFields] = useState({ name: '', email: '', company: '', message: '', website: '' });
  const [consent, setConsent] = useState(false);
  const [token, setToken] = useState('');
  const [error, setError] = useState('');
  const [pending, setPending] = useState(false);
  const [accepted, setAccepted] = useState(false);
  const [verificationKey, setVerificationKey] = useState(0);
  const quiet = useQuietMotion();
  /** Keeps Tab within the composer instead of allowing the browser chrome to take focus. */
  function containFocus(event: KeyboardEvent<HTMLDialogElement>) {
    if (event.key !== 'Tab') return;
    const controls = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input:not(:disabled), textarea:not(:disabled), iframe, [tabindex="0"]'))
      .filter(element => element.tabIndex >= 0 && !element.closest('[aria-hidden="true"]') && element.getClientRects().length > 0);
    const first = controls[0];
    const last = controls.at(-1);
    if (!first || !last) return;
    if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
    else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
  }
  useEffect(() => {
    const element = dialog.current;
    const opener = document.activeElement as HTMLElement | null;
    const overflow = document.body.style.overflow;
    element?.showModal();
    element?.querySelector<HTMLInputElement>('input[name="name"]')?.focus({ preventScroll: true });
    document.body.style.overflow = 'hidden';
    const controller = new AbortController();
    fetch('/api/contact', { signal: controller.signal }).then(async response => {
      if (!response.ok || !response.headers.get('content-type')?.includes('application/json')) throw new Error('Unavailable');
      const result: unknown = await response.json();
      if (result && typeof result === 'object' && 'available' in result && 'siteKey' in result && result.available === true && typeof result.siteKey === 'string' && result.siteKey) {
        setConfig({ available: true, siteKey: result.siteKey });
      } else setConfig({ available: false, siteKey: '' });
    }).catch(() => { if (!controller.signal.aborted) setConfig({ available: false, siteKey: '' }); });
    return () => { controller.abort(); request.current?.abort(); element?.close(); document.body.style.overflow = overflow; opener?.focus({ preventScroll: true }); };
  }, []);

  /** Retains the same idempotency key for a retry, but starts a new request when content changes. */
  function updateField(name: keyof typeof fields, value: string) {
    setFields(current => ({ ...current, [name]: value }));
    requestId.current = crypto.randomUUID();
    setError('');
  }

  /** Sends bounded form data to the same-origin endpoint; never treats a mailto link as delivery. */
  async function send(event: SyntheticEvent<HTMLFormElement>) {
    event.preventDefault();
    if (pending || !config?.available || !token || !consent) return;
    setPending(true); setError('');
    const controller = new AbortController();
    request.current = controller;
    const timeout = setTimeout(() => controller.abort(), 22000);
    try {
      const response = await fetch('/api/contact', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: controller.signal,
        body: JSON.stringify({ ...fields, consent, token, requestId: requestId.current }),
      });
      const result = await response.json();
      if (response.status !== 202 || result.accepted !== true) throw new Error(typeof result.error === 'string' ? result.error : 'Message was not accepted. Please try again.');
      setAccepted(true);
      setFields({ name: '', email: '', company: '', message: '', website: '' });
    } catch (error_) {
      let message = 'Unable to send. Please use the email link.';
      if (error_ instanceof Error) message = error_.message;
      if (controller.signal.aborted) message = 'Delivery could not be confirmed. Retry or use the email link.';
      setError(message);
    } finally {
      clearTimeout(timeout); setPending(false); setToken(''); setVerificationKey(value => value + 1);
    }
  }
  const draftBody = `Hi Shilpa,\n\n${fields.message}\n\n${fields.name}\n${fields.company}\n${fields.email}`;
  const draft = `mailto:shilpakalwar25@gmail.com?subject=${encodeURIComponent('Portfolio enquiry')}&body=${encodeURIComponent(draftBody)}`;
  let setupMessage = '';
  if (config === null) setupMessage = 'Checking message delivery…';
  else if (!config.available) setupMessage = 'Direct sending is not configured yet. You can write your message here and open it in your email app below.';
  else if (!token) setupMessage = 'Complete the spam-protection check to enable Send message.';
  return <dialog ref={dialog} className="contact-dialog" aria-labelledby="contact-dialog-title" aria-describedby="contact-dialog-description" onKeyDown={containFocus} onCancel={event => { event.preventDefault(); onClose(); }}>
    <motion.div className="contact-dialog-panel" initial={quiet ? false : { opacity: 0, y: 25, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .35 }}>
      <header className="chat-header"><span className="chat-avatar" aria-hidden="true">SG</span><div><h2 id="contact-dialog-title">Talk to Shilpa</h2><p>A direct message, not a chatbot.</p></div><button className="icon-button" aria-label="Close message dialog" onClick={onClose}><X size={21} /></button></header>
      <div className="chat-body">
        <div className="chat-bubble"><MessageCircle size={18} aria-hidden="true" /><p id="contact-dialog-description">Have a role or project in mind? Share the details and your email so I can reply.</p></div>
        {accepted ? <div className="message-accepted"><Check size={30} /><h3><output>Message accepted for delivery</output></h3><p>The email service accepted your message. Inbox delivery is not guaranteed; Shilpa can reply to the email address you provided.</p><button className="button button-secondary" onClick={onClose}>Done</button></div> : <form onSubmit={send} aria-label="Recruiter message" aria-busy={pending}>
          <fieldset disabled={pending} className="message-fields"><legend className="sr-only">Your contact details and message</legend>
            <div className="contact-form-row"><label>Your name<input autoFocus name="name" autoComplete="name" required maxLength={100} value={fields.name} onChange={event => updateField('name', event.target.value)} /></label><label>Your email<input name="email" type="email" autoComplete="email" required maxLength={254} value={fields.email} onChange={event => updateField('email', event.target.value)} /></label></div>
            <label>Company <span>(optional)</span><input name="company" autoComplete="organization" maxLength={120} value={fields.company} onChange={event => updateField('company', event.target.value)} /></label>
            <label htmlFor="recruiter-message">Your message</label><textarea id="recruiter-message" name="message" required minLength={10} maxLength={4000} rows={5} placeholder="Tell me about the role, team, or opportunity…" value={fields.message} onChange={event => updateField('message', event.target.value)} />
            <span className="message-count">{fields.message.length} / 4000</span>
            <div className="contact-honeypot" aria-hidden="true"><label>Leave this empty<input name="website" tabIndex={-1} autoComplete="off" value={fields.website} onChange={event => updateField('website', event.target.value)} /></label></div>
            <label className="contact-consent"><input type="checkbox" required checked={consent} onChange={event => setConsent(event.target.checked)} /><span>I agree to share these details with Shilpa by email. Please do not include confidential information.</span></label>
          </fieldset>
          {config?.available && <><p className="contact-privacy">Spam protection by Cloudflare Turnstile; email delivery by Resend. Details are used to send and reply to this enquiry.</p><Verification key={verificationKey} siteKey={config.siteKey} onToken={setToken} onError={setError} /></>}
          <output className="contact-setup">{setupMessage}</output>
          {error && <p className="contact-error" role="alert">{error}</p>}
          <div className="message-actions"><button className="button button-primary" type="submit" disabled={!config?.available || !token || !consent || pending}>{pending ? 'Sending…' : 'Send message'}<Send size={17} className={pending ? 'sending-icon' : ''} /></button><a href={draft} className="text-link"><Mail size={16} />Open email app instead</a></div>
          <p className="contact-privacy">The email-app option only prepares a draft. You must send it yourself.</p>
        </form>}
      </div>
    </motion.div>
  </dialog>;
}