// Generated by GitHub Copilot - Sep-30-2026
import { createContext, useContext, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { motion, useReducedMotion, useScroll } from 'motion/react';
import { ArrowRight, Braces, Cpu, Database, GitBranch, ShieldCheck } from 'lucide-react';
import { skills, type Flow } from '../data';

export const MotionPausedContext = createContext(false);

/** Combines the explicit playback control with the operating-system motion preference. */
export function useQuietMotion() {
  const paused = useContext(MotionPausedContext);
  const reduced = useReducedMotion();
  return paused || !!reduced;
}

/** Adds bounded pointer tilt without touch listeners or a permanent animation loop. */
export function TiltSurface({ children, className = '' }: Readonly<{ children: ReactNode; className?: string }>) {
  const quiet = useQuietMotion();
  return <div className={`tilt-surface ${className}`} onPointerMove={event => {
    if (quiet || event.pointerType !== 'mouse') return;
    const rect = event.currentTarget.getBoundingClientRect();
    event.currentTarget.style.setProperty('--tilt-x', `${((event.clientY - rect.top) / rect.height - .5) * -4}deg`);
    event.currentTarget.style.setProperty('--tilt-y', `${((event.clientX - rect.left) / rect.width - .5) * 5}deg`);
  }} onPointerLeave={event => {
    event.currentTarget.style.setProperty('--tilt-x', '0deg');
    event.currentTarget.style.setProperty('--tilt-y', '0deg');
  }}>{children}</div>;
}

/** Makes every stack layer visible and lets keyboard users inspect its engineering role. */
export function TechnologyEcosystem() {
  const [active, setActive] = useState(0);
  const quiet = useQuietMotion();
  return <div className="ecosystem" data-ambient="true">
    <div className="ecosystem-map">
      <svg className="ecosystem-wires" viewBox="0 0 1000 650" preserveAspectRatio="none" aria-hidden="true">
        {['M500 315 Q350 120 165 95', 'M500 315 Q650 100 835 95', 'M500 315 L165 315', 'M500 315 L835 315', 'M500 315 Q350 530 165 545', 'M500 315 Q650 530 835 545', 'M500 315 L500 570'].map((d, i) => <path key={d} d={d} className={active === i ? 'is-selected' : ''} />)}
      </svg>
      <div className="ecosystem-hub"><span className="hub-orbit" aria-hidden="true" /><Cpu size={29} /><strong>Software<br />Engineering</strong><span>ONE CONNECTED STACK</span></div>
      {skills.map((group, i) => <motion.div className={`ecosystem-node eco-${i} ${active === i ? 'is-selected' : ''}`} key={group.name} initial={quiet ? false : { opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .06 }}>
        <button aria-pressed={active === i} onClick={() => setActive(i)}><span>0{i + 1}</span><h3>{group.name}</h3><ArrowRight size={16} /></button>
        <p>{group.note}</p><div className="chip-list">{group.items.map(item => <span className="skill-chip" key={item}>{item}</span>)}</div>
      </motion.div>)}
    </div>
    <p className="ecosystem-readout" aria-live="polite"><span className="tiny-dot" />{skills[active].name} <ArrowRight size={15} /> {skills[active].note}</p>
  </div>;
}

/** Explains a compact development loop; selection is never controlled by an automatic timer. */
export function EngineeringCycle() {
  const [active, setActive] = useState(0);
  const stages = [
    ['Design', 'Understand the workflow. Shape a clear, accessible interface.'],
    ['Build', 'Create reusable Angular components and explicit state boundaries.'],
    ['Integrate', 'Connect REST APIs, application services, and persistent data.'],
    ['Test', 'Exercise behavior with Jasmine and Karma. Debug the edges.'],
    ['Deploy', 'Collaborate through Git and Agile delivery; support production.'],
    ['Improve', 'Refine usability, lazy loading, and maintainability.'],
  ];
  return <div className="engineering-cycle" data-ambient="true">
    <div className="cycle-core"><span className="hub-orbit" aria-hidden="true" /><Braces size={28} /><span>IDEA → EXPERIENCE</span></div>
    <ol>{stages.map(([name], i) => <li key={name}><button onClick={() => setActive(i)} aria-pressed={active === i}><span>0{i + 1}</span>{name}<ArrowRight size={15} /></button></li>)}</ol>
    <p aria-live="polite"><strong>{stages[active][0]}.</strong> {stages[active][1]}</p>
  </div>;
}

/** Presents readable ordered steps alongside decorative traveling signals and sequential reveals. */
export function AnimatedFlow({ flow, variant = 'normal' }: Readonly<{ flow: Flow; variant?: 'normal' | 'fallback' }>) {
  const quiet = useQuietMotion();
  return <div className={`flow-block signal-flow ${variant}`} data-ambient="true">
    <h4><GitBranch size={17} />{flow.title}</h4>
    <ol className="architecture-flow">{flow.steps.map((step, index) => <motion.li key={step} style={{ '--step': index } as CSSProperties}
      initial={quiet ? false : { opacity: 0, y: 12 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .075 }}>
      <span className="flow-number">{String(index + 1).padStart(2, '0')}</span><span>{step}</span>
      {index < flow.steps.length - 1 && <svg className="signal-connector" viewBox="0 0 40 20" aria-hidden="true"><path d="M1 10 H35 M29 4 L35 10 L29 16" /><path className="travel-signal" d="M1 10 H35" /></svg>}
    </motion.li>)}</ol>
  </div>;
}

/** Keeps security and data responsibilities distinct from AI generation. */
export function StudyBoundaries() {
  return <div className="boundary-grid">
    <div><ShieldCheck size={23} /><h4>Security boundary</h4><p>JWT · Spring Security</p><span>Angular route guards + HTTP interceptors connect the session to protected backend APIs.</span></div>
    <div><Database size={23} /><h4>Persistent learning</h4><p>JPA/Hibernate · MySQL</p><span>Document records, Q&A history, quiz attempts, and scores remain part of the learning workflow.</span></div>
  </div>;
}

/** Illuminates the timeline with actual scroll progress, with a static reduced-motion alternative. */
export function CareerTimeline({ children }: Readonly<{ children: ReactNode }>) {
  const ref = useRef<HTMLDivElement>(null);
  const quiet = useQuietMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start 75%', 'end 65%'] });
  return <div className="timeline" ref={ref} data-ambient="true"><motion.div className="timeline-progress" aria-hidden="true" style={{ scaleY: quiet ? 1 : scrollYProgress }} />{children}</div>;
}

/** Decorative particles are finite in number and share the global/offscreen CSS playback gates. */
export function HeroParticles() {
  return <div className="hero-particles" aria-hidden="true">{Array.from({ length: 12 }, (_, i) => <i key={i} style={{ '--i': i, left: `${8 + (i * 23) % 85}%`, top: `${8 + (i * 17) % 85}%` } as CSSProperties} />)}<span className="code-mote">{'{ }'}</span><span className="code-mote second">{'</>'}</span></div>;
}