// Generated by GitHub Copilot - Sep-30-2026
import { useEffect, useRef, useState } from 'react';
import { useReducedMotion } from 'motion/react';
import type { BufferGeometry, Material, Scene, WebGLRenderer } from 'three';

/** Adds a decorative, locally rendered orbital scene without exposing canvas content to assistive technology. */
export default function EngineeringScene({ paused }: Readonly<{ paused: boolean }>) {
  const hostRef = useRef<HTMLDivElement>(null);
  const pausedRef = useRef(paused);
  const synchronizeRef = useRef<(() => void) | null>(null);
  const reducedMotion = useReducedMotion();
  const [rendererKind, setRendererKind] = useState<'fallback' | 'webgl'>('fallback');

  // Generated by GitHub Copilot - Sep-30-2026
  /** Updates playback independently of renderer ownership, preserving the WebGL context. */
  useEffect(() => {
    pausedRef.current = paused;
    synchronizeRef.current?.();
  }, [paused]);

  // Generated by GitHub Copilot - Sep-30-2026
  /** Owns the async scene and all GPU/browser resources; reduced motion never creates a renderer. */
  useEffect(() => {
    const host = hostRef.current;
    setRendererKind('fallback');
    if (!host || reducedMotion !== false) return;

    let cancelled = false;
    let disposed = false;
    let renderer: WebGLRenderer | undefined;
    let scene: Scene | undefined;
    let resizeObserver: ResizeObserver | undefined;
    let intersectionObserver: IntersectionObserver | undefined;
    let frame: number | null = null;
    let intersecting = false;
    let hasSize = false;
    let lastFrame = 0;
    let elapsed = 0;
    let targetX = 0;
    let targetY = 0;
    let synchronize = stop;
    const geometries = new Set<BufferGeometry>();
    const materials = new Set<Material>();
    const frameInterval = 1000 / 30;

    // Generated by GitHub Copilot - Sep-30-2026
    /** Cancels scheduled work rather than polling while the decoration is inactive. */
    function stop() {
      if (frame !== null) cancelAnimationFrame(frame);
      frame = null;
      lastFrame = 0;
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Allows remaining resources to be released even if a lost GPU context rejects one release. */
    function safelyRelease(release: () => void) {
      try {
        release();
      } catch {
        // Context loss must not escape into the surrounding portfolio UI.
      }
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Releases each shared geometry/material once and detaches every scene object and browser hook. */
    function dispose() {
      if (disposed) return;
      disposed = true;
      stop();
      if (synchronizeRef.current === synchronize) synchronizeRef.current = null;
      resizeObserver?.disconnect();
      intersectionObserver?.disconnect();
      document.removeEventListener('visibilitychange', onVisibilityChange);
      window.removeEventListener('pointermove', onPointerMove);
      window.removeEventListener('pointerout', onPointerOut);
      window.removeEventListener('blur', resetPointer);
      window.removeEventListener('resize', onWindowResize);
      window.removeEventListener('scroll', onViewportChange, true);
      const canvas = renderer?.domElement;
      canvas?.removeEventListener('webglcontextlost', onContextLost);
      scene?.clear();
      for (const geometry of geometries) safelyRelease(geometry.dispose.bind(geometry));
      for (const material of materials) safelyRelease(material.dispose.bind(material));
      geometries.clear();
      materials.clear();
      if (renderer) {
        const ownedRenderer = renderer;
        safelyRelease(ownedRenderer.dispose.bind(ownedRenderer));
        safelyRelease(ownedRenderer.forceContextLoss.bind(ownedRenderer));
      }
      canvas?.remove();
      renderer = undefined;
      scene = undefined;
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Restores the parent's CSS fallback on unsupported WebGL or a render/context failure. */
    function fallback() {
      dispose();
      if (!cancelled) setRendererKind('fallback');
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Retires a lost context instead of attempting an expensive automatic recreation loop. */
    function onContextLost(event: Event) {
      event.preventDefault();
      fallback();
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Returns the scene gently to its neutral orientation. */
    function resetPointer() {
      targetX = 0;
      targetY = 0;
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Resets pointer tilt when the pointer leaves the browser rather than a portrait child. */
    function onPointerOut(event: PointerEvent) {
      if (event.relatedTarget === null) resetPointer();
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Observes pointer coordinates passively so portrait overlays and keyboard interaction remain untouched. */
    function onPointerMove(event: PointerEvent) {
      if (disposed || pausedRef.current || !intersecting || document.hidden || event.pointerType === 'touch') return;
      const bounds = host!.getBoundingClientRect();
      if (!bounds.width || !bounds.height) return;
      const x = (event.clientX - bounds.left) / bounds.width;
      const y = (event.clientY - bounds.top) / bounds.height;
      targetY = x >= 0 && x <= 1 && y >= 0 && y <= 1 ? (x - .5) * .16 : 0;
      targetX = x >= 0 && x <= 1 && y >= 0 && y <= 1 ? (y - .5) * .12 : 0;
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Stops immediately in hidden tabs and resumes only when every playback gate permits it. */
    function onVisibilityChange() {
      resetPointer();
      synchronize();
    }

    let resize = stop;

    // Generated by GitHub Copilot - Sep-30-2026
    /** Handles device-pixel-ratio changes and provides a resize fallback for older browsers. */
    function onWindowResize() {
      resize();
      if (!intersectionObserver) onViewportChange();
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Provides event-driven offscreen detection when IntersectionObserver is unavailable. */
    function onViewportChange() {
      const bounds = host!.getBoundingClientRect();
      intersecting = bounds.bottom > 0 && bounds.right > 0
        && bounds.top < window.innerHeight && bounds.left < window.innerWidth;
      synchronize();
    }

    // Generated by GitHub Copilot - Sep-30-2026
    /** Imports Three.js only for motion-enabled clients and constructs a small, asset-free scene. */
    async function initialize() {
      try {
        const THREE = await import('three');
        if (cancelled || disposed) return;

        renderer = new THREE.WebGLRenderer({
          alpha: true,
          antialias: true,
          powerPreference: 'low-power',
          preserveDrawingBuffer: false,
        });
        renderer.setClearColor(0x000000, 0);
        renderer.outputColorSpace = THREE.SRGBColorSpace;
        const canvas = renderer.domElement;
        canvas.setAttribute('aria-hidden', 'true');
        canvas.style.cssText = 'display:block;width:100%;height:100%;pointer-events:none;';
        canvas.addEventListener('webglcontextlost', onContextLost);

        scene = new THREE.Scene();
        const camera = new THREE.PerspectiveCamera(34, 1, .1, 40);
        camera.position.set(0, 0, 9);
        const composition = new THREE.Group();
        scene.add(composition);
        scene.add(new THREE.HemisphereLight(0xf1efff, 0x7774ae, 2.5));
        const keyLight = new THREE.DirectionalLight(0xffffff, 3);
        keyLight.position.set(-3, 4, 6);
        scene.add(keyLight);

        // Generated by GitHub Copilot - Sep-30-2026
        /** Registers geometry immediately so partial initialization is also safe to tear down. */
        function ownGeometry<T extends BufferGeometry>(geometry: T): T {
          geometries.add(geometry);
          return geometry;
        }

        // Generated by GitHub Copilot - Sep-30-2026
        /** Registers materials independently of scene attachment, including shared satellite materials. */
        function ownMaterial<T extends Material>(material: T): T {
          materials.add(material);
          return material;
        }

        const pearl = ownMaterial(new THREE.MeshStandardMaterial({
          color: 0xedbeff, emissive: 0x6b287a, emissiveIntensity: .5, metalness: .25, roughness: .3,
        }));
        const indigo = ownMaterial(new THREE.MeshStandardMaterial({
          color: 0xec78bf, emissive: 0x792455, emissiveIntensity: .4, metalness: .3, roughness: .35,
        }));
        const orbGeometry = ownGeometry(new THREE.SphereGeometry(.082, 16, 12));
        const orbitSpecifications = [
          { radius: 1.82, x: .45, y: -.24, z: -.32, color: 0xc084fc, opacity: .8, speed: .42 },
          { radius: 2.03, x: -.5, y: .35, z: .5, color: 0xec78bf, opacity: .55, speed: -.3 },
          { radius: 2.2, x: .27, y: .54, z: -.66, color: 0xd7b6ef, opacity: .35, speed: .23 },
        ];
        const orbits = orbitSpecifications.map(
          // Generated by GitHub Copilot - Sep-30-2026
          /** Creates an orbital plane with two satellites sharing low-resolution sphere geometry. */
          (specification, index) => {
            const group = new THREE.Group();
            group.rotation.set(specification.x, specification.y, specification.z);
            composition.add(group);
            const geometry = ownGeometry(new THREE.TorusGeometry(specification.radius, .008, 6, 144));
            const material = ownMaterial(new THREE.MeshBasicMaterial({
              color: specification.color, transparent: true, opacity: specification.opacity, depthWrite: false,
            }));
            group.add(new THREE.Mesh(geometry, material));
            const satellite = new THREE.Mesh(orbGeometry, index === 1 ? indigo : pearl);
            const companion = new THREE.Mesh(orbGeometry, pearl);
            companion.scale.setScalar(.48);
            group.add(satellite, companion);
            return { group, satellite, companion, specification, phase: index * 2.1 };
          },
        );

        const coreGeometry = ownGeometry(new THREE.IcosahedronGeometry(.58, 0));
        const coreEdges = ownGeometry(new THREE.EdgesGeometry(coreGeometry));
        const coreMaterial = ownMaterial(new THREE.LineBasicMaterial({
          color: 0x9690d8, transparent: true, opacity: .2, depthWrite: false,
        }));
        const core = new THREE.LineSegments(coreEdges, coreMaterial);
        composition.add(core);

        const positions = new Float32Array(36 * 3);
        for (let index = 0; index < 36; index += 1) {
          const angle = index * 2.3999632297;
          const radius = 1.35 + (index % 7) * .145;
          positions[index * 3] = Math.cos(angle) * radius;
          positions[index * 3 + 1] = Math.sin(angle) * radius;
          positions[index * 3 + 2] = Math.sin(index * 1.7) * .35;
        }
        const pointGeometry = ownGeometry(new THREE.BufferGeometry());
        pointGeometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
        const pointMaterial = ownMaterial(new THREE.PointsMaterial({
          color: 0xebbbfa, size: .023, transparent: true, opacity: .65, depthWrite: false,
        }));
        const points = new THREE.Points(pointGeometry, pointMaterial);
        composition.add(points);

        // Generated by GitHub Copilot - Sep-30-2026
        /** Evaluates every playback gate without scheduling work in inactive states. */
        function canAnimate() {
          return !cancelled && !disposed && hasSize && intersecting && !document.hidden && !pausedRef.current;
        }

        // Generated by GitHub Copilot - Sep-30-2026
        /** Advances bounded deltas at approximately 30 fps with restrained orbital and pointer motion. */
        function tick(timestamp: number) {
          frame = null;
          if (!canAnimate()) { stop(); return; }
          const delta = lastFrame === 0 ? frameInterval : timestamp - lastFrame;
          if (delta >= frameInterval - .5) {
            lastFrame = timestamp;
            const seconds = Math.min(delta / 1000, .08);
            elapsed += seconds;
            const easing = 1 - Math.exp(-seconds * 3);
            composition.rotation.x += (targetX - composition.rotation.x) * easing;
            composition.rotation.y += (targetY - composition.rotation.y) * easing;
            for (const orbit of orbits) {
              const angle = elapsed * orbit.specification.speed + orbit.phase;
              orbit.satellite.position.set(Math.cos(angle) * orbit.specification.radius, Math.sin(angle) * orbit.specification.radius, 0);
              orbit.companion.position.set(Math.cos(angle + 2.6) * orbit.specification.radius, Math.sin(angle + 2.6) * orbit.specification.radius, 0);
              orbit.group.rotation.z = orbit.specification.z + Math.sin(elapsed * .09 + orbit.phase) * .045;
            }
            core.rotation.set(elapsed * .065, elapsed * .09, .2);
            points.rotation.z = elapsed * .012;
            try {
              renderer!.render(scene!, camera);
            } catch {
              fallback();
              return;
            }
          }
          if (canAnimate()) frame = requestAnimationFrame(tick);
        }

        // Generated by GitHub Copilot - Sep-30-2026
        /** Starts exactly one animation chain or cancels it immediately when a gate closes. */
        synchronize = function synchronizePlayback() {
          if (!canAnimate()) { stop(); return; }
          frame ??= requestAnimationFrame(tick);
        };

        // Generated by GitHub Copilot - Sep-30-2026
        /** Fits a bounding sphere to the narrower host dimension so tilted rings stay inside the canvas. */
        resize = function resizeScene() {
          if (disposed || !renderer) return;
          try {
            const width = host!.clientWidth;
            const height = host!.clientHeight;
            hasSize = width > 0 && height > 0;
            if (hasSize) {
              renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 1.5));
              renderer.setSize(width, height, false);
              camera.aspect = width / height;
              const verticalHalfFov = THREE.MathUtils.degToRad(camera.fov / 2);
              const limitingHalfFov = Math.atan(Math.tan(verticalHalfFov) * Math.min(1, camera.aspect));
              camera.position.z = 2.48 / Math.sin(limitingHalfFov);
              camera.far = camera.position.z + 10;
              camera.updateProjectionMatrix();
              // A paused scene may repaint on resize, but never runs an animation loop.
              if (intersecting && !document.hidden) renderer.render(scene!, camera);
            }
            synchronize();
          } catch {
            fallback();
          }
        };

        // Place satellites before the first static render, including an initially paused mount.
        for (const orbit of orbits) {
          orbit.satellite.position.set(Math.cos(orbit.phase) * orbit.specification.radius, Math.sin(orbit.phase) * orbit.specification.radius, 0);
          orbit.companion.position.set(Math.cos(orbit.phase + 2.6) * orbit.specification.radius, Math.sin(orbit.phase + 2.6) * orbit.specification.radius, 0);
        }
        host!.appendChild(canvas);
        synchronizeRef.current = synchronize;
        onViewportChange();
        resize();
        if (disposed) return;

        if (typeof ResizeObserver !== 'undefined') {
          resizeObserver = new ResizeObserver(resize);
          resizeObserver.observe(host!);
        }
        if (typeof IntersectionObserver !== 'undefined') {
          intersectionObserver = new IntersectionObserver(
            // Generated by GitHub Copilot - Sep-30-2026
            /** Suspends rendering whenever the sole observed host leaves the viewport. */
            (entries) => {
              if (disposed) return;
              for (const entry of entries) {
                if (entry.target === host) intersecting = entry.isIntersecting;
              }
              synchronize();
            },
          );
          intersectionObserver.observe(host!);
        } else {
          window.addEventListener('scroll', onViewportChange, { passive: true, capture: true });
        }
        document.addEventListener('visibilitychange', onVisibilityChange);
        window.addEventListener('resize', onWindowResize, { passive: true });
        window.addEventListener('pointermove', onPointerMove, { passive: true });
        window.addEventListener('pointerout', onPointerOut, { passive: true });
        window.addEventListener('blur', resetPointer);
        setRendererKind('webgl');
      } catch {
        fallback();
      }
    }

    void initialize();

    // Generated by GitHub Copilot - Sep-30-2026
    /** Invalidates pending imports before releasing resources, including React Strict Mode remounts. */
    return () => {
      cancelled = true;
      dispose();
    };
  }, [reducedMotion]);

  return <div ref={hostRef} className="engineering-scene" data-renderer={reducedMotion === false ? rendererKind : 'fallback'} aria-hidden="true" />;
}