// Generated by GitHub Copilot - Sep-30-2026
import { lazy, Suspense } from 'react';
import { Code2, Layers3, Sparkles, ArrowUpRight } from 'lucide-react';
import { portrait } from '../media';
import { HeroParticles } from './EngineeringVisuals';

const EngineeringScene = lazy(() => import('./EngineeringScene'));

/** Combines a real supplied portrait with decorative, independently pausable 3D. */
export default function HeroPortrait({ paused }: Readonly<{ paused: boolean }>) {
  return (
    <div className="portrait-stage" data-ambient="true">
      <HeroParticles />
      <div className="portrait-halo" aria-hidden="true" />
      <Suspense fallback={<div className="orbit-fallback" aria-hidden="true" />}>
        <EngineeringScene paused={paused} />
      </Suspense>
      <div className={`portrait-frame ${portrait.src ? 'has-portrait' : 'without-portrait'}`}>
        {portrait.src ? (
          <img src={portrait.src} alt={portrait.alt} width="768" height="1365" fetchPriority="high" decoding="async" />
        ) : (
          <div className="portrait-monogram" aria-label="Shilpa Gupta monogram">
            <span className="monogram-code">&lt;engineer&gt;</span>
            <span className="monogram-initials">sg<span>.</span></span>
            <span className="monogram-code">&lt;/engineer&gt;</span>
          </div>
        )}
        <div className="portrait-signature"><span>Shilpa Gupta</span><ArrowUpRight size={21} /></div>
      </div>
      <div className="floating-tag tag-frontend"><span className="tag-icon"><Code2 size={22} /></span><span><strong>Frontend precision</strong><small>Angular · TypeScript</small></span></div>
      <div className="floating-tag tag-backend-detail"><span className="tag-icon"><Sparkles size={22} /></span><span><strong>Connected applications</strong><small>Java · Node.js · REST APIs</small></span></div>
      <div className="floating-tag tag-backend"><Layers3 size={18} /><span>Full-stack perspective</span></div>
      <div className="orbit-technologies" aria-label="Hero technology ecosystem">
        {['Angular', 'TypeScript', 'Java', 'Spring Boot', 'Node.js', 'MongoDB', 'C# / .NET'].map((technology, i) => <span className={`orbit-node orbit-node-${i}`} key={technology}><span>{technology}</span></span>)}
      </div>
      <span className="orbit-caption">SOFTWARE ENGINEERING · FULL-STACK DEVELOPMENT</span>
    </div>
  );
}