// Generated by GitHub Copilot - Sep-30-2026
import { useEffect, useRef } from 'react';
import { motion, useScroll, useSpring } from 'motion/react';
import { useQuietMotion } from './EngineeringVisuals';

/** Tracks reading progress and paints pointer highlights only on hovered cards, never in a busy loop. */
export default function PageMotion() {
  const quiet = useQuietMotion();
  const { scrollYProgress } = useScroll();
  const progress = useSpring(scrollYProgress, { stiffness: 180, damping: 32 });
  const frame = useRef(0);
  useEffect(() => {
    if (quiet || !matchMedia('(hover: hover) and (pointer: fine)').matches) return;
    let previous: HTMLElement | null = null;
    /** Coalesces mouse events into one paint and does not retain visitor pointer data. */
    const highlight = (event: PointerEvent) => {
      if (event.pointerType !== 'mouse') return;
      cancelAnimationFrame(frame.current);
      frame.current = requestAnimationFrame(() => {
        const card = event.target instanceof Element ? event.target.closest<HTMLElement>('.experience-card, .award-card, .certification, .ecosystem-node, .contact-invitation') : null;
        if (previous && previous !== card) previous.classList.remove('pointer-active');
        if (card) {
          const bounds = card.getBoundingClientRect();
          card.style.setProperty('--pointer-x', `${event.clientX - bounds.left}px`);
          card.style.setProperty('--pointer-y', `${event.clientY - bounds.top}px`);
          card.classList.add('pointer-active');
        }
        previous = card;
      });
    };
    /** Clears decoration when the pointer exits the viewport. */
    const leave = () => { cancelAnimationFrame(frame.current); previous?.classList.remove('pointer-active'); };
    document.addEventListener('pointermove', highlight, { passive: true });
    document.documentElement.addEventListener('pointerleave', leave);
    return () => { leave(); document.removeEventListener('pointermove', highlight); document.documentElement.removeEventListener('pointerleave', leave); };
  }, [quiet]);
  return <motion.div className="reading-progress" aria-hidden="true" style={{ scaleX: quiet ? scrollYProgress : progress }} />;
}