// Generated by GitHub Copilot - Sep-30-2026
import { useId, useState, type CSSProperties } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowRight, Check, CircleCheck, Layers3, RotateCcw, ShieldCheck, Sparkles } from 'lucide-react';
import type { Project } from '../data';
import { ProjectVisual } from './Visuals';
import { AnimatedFlow, StudyBoundaries, TiltSurface, useQuietMotion } from './EngineeringVisuals';

/** Presents unaltered supplied screens in a browser frame, with explicit user-controlled switching. */
export function BrowserShowcase({ project, onOpen }: Readonly<{ project: Project; onOpen: () => void }>) {
  const [view, setView] = useState(0);
  const quiet = useQuietMotion();
  const options = project.id === 'studymate' ? [{ index: 0, label: 'Light dashboard' }, { index: 1, label: 'Dark dashboard' }, { index: 2, label: 'Document Q&A' }]
    : [{ index: 0, label: 'Ordering assistant' }, { index: 3, label: 'Meal Builder' }, { index: 4, label: 'Meal result' }];
  const image = project.screenshots[view];
  if (!image) return <ProjectVisual project={project} interactive />;
  const features = project.id === 'studymate' ? ['PDF Upload', 'Document Q&A', 'Quiz Generator', 'Q&A History', 'Attempt Analytics', 'Persistent Learning']
    : ['Natural-language ordering', 'Menu matching', 'Ingredient validation', 'Intent processing', 'Cart actions', 'Fallback parsing'];
  return <div className="product-stage" data-ambient="true">
    <div className="screen-selector" aria-label={`${project.name} preview screens`}>{options.filter(option => project.screenshots[option.index]).map(option => <button key={option.index} aria-pressed={view === option.index} onClick={() => setView(option.index)}>{option.label}</button>)}</div>
    <TiltSurface className="browser-tilt"><div className="browser-frame">
      <div className="browser-chrome"><span className="browser-dots" aria-hidden="true"><i /><i /><i /></span><span>{project.id === 'studymate' ? 'studymate.ai / learning workspace' : 'pizzeria / intelligent ordering'}</span><ShieldCheck size={14} aria-hidden="true" /></div>
      <figure className="real-screenshot">
        <button className="screen-open" onClick={onOpen} aria-label={`Inspect ${project.name} original screen and case study`}>
        <motion.img key={image.src} initial={quiet ? false : { opacity: .5 }} animate={{ opacity: 1 }} transition={{ duration: .3 }} src={image.src} alt={image.alt} loading="lazy" decoding="async" />
        </button>
        <figcaption>{image.caption}</figcaption>
      </figure>
    </div></TiltSurface>
    <div className="feature-constellation" aria-label={`${project.name} features`}>{features.map((feature, i) => <span key={feature} style={{ '--step': i } as CSSProperties}><CircleCheck size={13} />{feature}</span>)}</div>
    <span className="original-label">ORIGINAL PRODUCT CAPTURES · EXPLORE ALL IN THE CASE STUDY</span>
  </div>;
}

/** Demonstrates validated intent flow locally; no model request or order is submitted. */
export function PizzaAssistant() {
  const [fallback, setFallback] = useState(false);
  return <div className="assistant-story" data-ambient="true">
    <div className="story-heading"><div><span className="eyebrow">LANGUAGE → VALIDATED ACTION</span><h4>Not a chatbot on the side.<br /><em>An ordering interface.</em></h4></div><Sparkles size={29} /></div>
    <div className="assistant-conversation"><span className="message-role">USER / ILLUSTRATIVE REQUEST</span><blockquote>“I want a spicy chicken pizza with extra cheese”</blockquote><div className="intent-tokens"><span>preference: spicy</span><span>ingredient: chicken</span><span>customization: extra cheese</span></div></div>
    <div className="pipeline-controls"><span>Explore the processing path</span><div><button aria-pressed={!fallback} onClick={() => setFallback(false)}>Standard processing</button><button aria-pressed={fallback} onClick={() => setFallback(true)}>Simulate fallback</button></div></div>
    <AnimatedFlow variant={fallback ? 'fallback' : 'normal'} flow={{ title: fallback ? 'Resilience path · fallback parsing' : 'Pizza Assistant · natural-language understanding', steps: fallback
      ? ['Primary processing unavailable', 'Fallback parser', 'Menu matching', 'Ingredient validation', 'Order intent', 'Cart action', 'Order workflow']
      : ['Natural-language understanding', 'Menu matching', 'Ingredient validation', 'Order intent', 'Cart action', 'Order workflow'] }} />
    <p className={`pipeline-result ${fallback ? 'fallback' : ''}`} aria-live="polite"><ShieldCheck size={18} />{fallback ? 'Fallback parsing keeps order processing moving through the same validation boundary.' : 'The assistant interprets the request. Menu and ingredient validation gate the cart action.'}</p>
    <p className="demo-disclaimer">Interactive architecture illustration. No live service call, availability check, or order is made here.</p>
  </div>;
}

const ingredients = [
  { id: 'cheese', name: 'Extra cheese', price: 40, color: '#ffd779', points: [[25, 28], [60, 22], [44, 65], [70, 60], [23, 58]] },
  { id: 'pepper', name: 'Peppers', price: 25, color: '#82d9a3', points: [[35, 20], [68, 38], [28, 67], [58, 71], [43, 45]] },
  { id: 'chicken', name: 'Chicken', price: 60, color: '#eeab7b', points: [[44, 23], [24, 43], [70, 52], [40, 73], [53, 51]] },
  { id: 'chilli', name: 'Chilli', price: 15, color: '#fa7d82', points: [[54, 32], [35, 53], [66, 70], [72, 26], [23, 28]] },
] as const;

/** Uses bounded local choices and explicit sample pricing; never represents a real checkout or menu. */
export function MealBuilder() {
  const id = useId();
  const [base, setBase] = useState('classic');
  const [selected, setSelected] = useState<string[]>(['cheese']);
  const [built, setBuilt] = useState(false);
  const quiet = useQuietMotion();
  const basePrice = base === 'classic' ? 180 : 210;
  const total = basePrice + ingredients.reduce((sum, item) => sum + (selected.includes(item.id) ? item.price : 0), 0);
  /** Changes a whitelisted ingredient and invalidates the previous local build confirmation. */
  function toggleIngredient(ingredient: string) {
    setSelected(current => current.includes(ingredient) ? current.filter(item => item !== ingredient) : [...current, ingredient]);
    setBuilt(false);
  }
  return <div className="meal-builder" data-ambient="true" aria-labelledby={`${id}-title`}>
    <div className="meal-intro"><span className="eyebrow">CUSTOMIZATION LAB / INTERACTIVE CONCEPT</span><h4 id={`${id}-title`}>Smart Meal Builder<span>Make it yours.</span></h4><p>Choose a base. Layer the ingredients. Watch composition and price respond together.</p><p className="demo-disclaimer">Illustrative portfolio demo with sample ₹ prices—not the actual menu or checkout. The original product’s natural-language Meal Builder is shown in the screenshots above.</p></div>
    <div className="meal-workbench">
      <div className="meal-controls">
        <fieldset><legend>01 / Choose base</legend><div className="base-options">{[{ id: 'classic', label: 'Classic', price: 180 }, { id: 'thin', label: 'Thin crust', price: 210 }].map(option => <label key={option.id}><input type="radio" name={`${id}-base`} value={option.id} checked={base === option.id} onChange={() => { setBase(option.id); setBuilt(false); }} /><span>{option.label}<small>₹{option.price}</small></span></label>)}</div></fieldset>
        <fieldset><legend>02 / Select ingredients & customize toppings</legend><div className="ingredient-options">{ingredients.map(item => <button key={item.id} aria-pressed={selected.includes(item.id)} onClick={() => toggleIngredient(item.id)} style={{ '--ingredient': item.color } as CSSProperties}><span className="ingredient-dot" /><span>{item.name}<small>+ ₹{item.price}</small></span>{selected.includes(item.id) && <Check size={16} />}</button>)}</div></fieldset>
      </div>
      <div className="pizza-lab-visual"><div className={`pizza-composition-demo ${base}`} role="img" aria-label={`Illustrative ${base === 'classic' ? 'classic' : 'thin crust'} pizza with ${selected.length ? ingredients.filter(item => selected.includes(item.id)).map(item => item.name).join(', ') : 'no extra toppings'}`}>
        <div className="pizza-sauce" /><div className="pizza-cheese" />
        <AnimatePresence>{ingredients.filter(item => selected.includes(item.id)).flatMap(item => item.points.map(([x, y], index) => <motion.i key={`${item.id}-${index}`} className={`pizza-topping topping-${item.id}`} style={{ left: `${x}%`, top: `${y}%`, background: item.color }} initial={quiet ? false : { opacity: 0, y: -60, scale: .3, rotate: -45 }} animate={{ opacity: 1, y: 0, scale: 1, rotate: index * 38 }} exit={{ opacity: 0, scale: .2 }} transition={{ delay: quiet ? 0 : index * .04, type: 'spring', stiffness: 200, damping: 18 }} />))}</AnimatePresence>
      </div><span className="pizza-lab-caption"><Layers3 size={15} /> LIVE LOCAL COMPOSITION</span></div>
      <div className="meal-total"><span>03 / Calculate sample price</span><output aria-label="Sample meal price" aria-live="polite"><motion.strong key={total} initial={quiet ? false : { y: 9, opacity: .3 }} animate={{ y: 0, opacity: 1 }}>₹{total}</motion.strong><small>Base ₹{basePrice} + toppings ₹{total - basePrice}</small></output>
        <button className="button button-primary" onClick={() => setBuilt(true)}>Build personalized meal <ArrowRight size={17} /></button>
        <button className="meal-reset" onClick={() => { setBase('classic'); setSelected(['cheese']); setBuilt(false); }}><RotateCcw size={14} />Reset demo</button>
        <p className="meal-confirmation" role="status">{built ? `Personalized concept built at ₹${total}. No real order placed.` : 'Your selections update the local composition instantly.'}</p>
      </div>
    </div>
  </div>;
}

/** Connects each original project capture to its own concise engineering story. */
export function ProjectStory({ project }: Readonly<{ project: Project }>) {
 // if (project.id === 'pizzeria') return <div className="project-story"><PizzaAssistant /><MealBuilder /></div>;
  //if (project.id === 'studymate') return <div className="project-story study-story"><div className="story-heading"><div><span className="eyebrow">DOCUMENT → UNDERSTANDING → PRACTICE</span><h4>A learning loop, not a one-off answer.</h4></div><Sparkles size={25} /></div><AnimatedFlow flow={project.flows[0]} /><AnimatedFlow flow={project.flows[1]} /><StudyBoundaries /></div>;
  return null;
}