// Generated by GitHub Copilot - Sep-30-2026
import { useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import {
  ArrowDown,
  ArrowRight,
  Bookmark,
  Check,
  Code2,
  Database,
  FileText,
  Layers3,
  Search,
  ShieldCheck,
  Sparkles,
  Terminal,
  WandSparkles,
} from 'lucide-react';
import type { Flow, Project } from '../data';

/** Illustrates connected application layers while respecting reduced motion. */
export function HeroVisual() {
  const reduced = useReducedMotion();
  return (
    <div className="hero-visual" aria-label="Illustration of connected frontend, backend, and data layers">
      <div className="visual-grid" aria-hidden="true" />
      <div className="visual-topline">
        <span className="tiny-dot" /> FROM INTERFACE TO INTELLIGENCE <span>01 / 03</span>
      </div>
      <motion.div
        className="architecture-sheet"
        initial={reduced ? false : { opacity: 0, y: 28, rotate: -3 }}
        animate={{ opacity: 1, y: 0, rotate: -3 }}
        transition={{ delay: .25, duration: .8 }}
      >
        <div className="sheet-heading">
          <Layers3 size={16} />
          <span>the bigger picture</span>
          <span className="window-dots">•••</span>
        </div>
        <div className="layer-row">
          <span className="layer-icon"><Code2 size={21} /></span>
          <div>
            <strong>Thoughtful interfaces</strong>
            <span>Angular · TypeScript · State</span>
          </div>
          <span className="layer-index">01</span>
        </div>
        <div className="layer-connector"><span /><ArrowDown size={14} /></div>
        <div className="layer-row">
          <span className="layer-icon"><Terminal size={21} /></span>
          <div>
            <strong>Connected systems</strong>
            <span>Spring Boot · Node.js · REST</span>
          </div>
          <span className="layer-index">02</span>
        </div>
        <div className="layer-connector"><span /><ArrowDown size={14} /></div>
        <div className="layer-row">
          <span className="layer-icon"><Database size={21} /></span>
          <div>
            <strong>Data that works</strong>
            <span>MySQL · MongoDB</span>
          </div>
          <span className="layer-index">03</span>
        </div>
      </motion.div>
      <motion.div
        className="intelligence-note"
        initial={reduced ? false : { opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: .6, duration: .7 }}
      >
        <Sparkles size={19} />
        <div>
          <strong>A little intelligence.</strong>
          <span>A lot of possibility.</span>
        </div>
        <span className="note-tag">+ AI</span>
      </motion.div>
      <div className="visual-bottomline">
        <span>DESIGNED TO CONNECT.</span>
        <span>BUILT TO WORK.</span>
      </div>
    </div>
  );
}

/** Presents ordered architecture steps with reduced-motion-aware reveals. */
export function ArchitectureFlow({ flow }: Readonly<{ flow: Flow }>) {
  const reduced = useReducedMotion();
  return (
    <div className="flow-block">
      <h4>{flow.title}</h4>
      <ol className="architecture-flow">
        {flow.steps.map((step, index) => (
          <motion.li
            key={step}
            initial={reduced ? false : { opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: index * .055 }}
          >
            <span className="flow-number">{String(index + 1).padStart(2, '0')}</span>
            <span>{step}</span>
            {index < flow.steps.length - 1 && (
              <ArrowRight className="flow-arrow" size={14} aria-hidden="true" />
            )}
          </motion.li>
        ))}
      </ol>
    </div>
  );
}

/** Shows the StudyMate workflow explicitly as an illustration, not a screenshot. */
export function StudyVisual() {
  return (
    <div
      className="study-visual visual-inner"
      aria-label="Illustrated StudyMate document-to-learning workflow, not a product screenshot"
    >
      <div className="illustration-heading">
        <span className="visual-brand"><Sparkles size={17} /> StudyMate.AI</span>
        <span>DOCUMENT → KNOWLEDGE</span>
      </div>
      <div className="study-composition">
        <div className="document-illustration">
          <div className="document-icon"><FileText size={23} /></div>
          <span className="document-label">YOUR STUDY MATERIAL</span>
          <strong>One document.<br />More possibilities.</strong>
          <div className="document-lines" aria-hidden="true"><i /><i /><i /><i /></div>
          <span className="document-footer"><ShieldCheck size={12} /> SHA-256 duplicate detection</span>
        </div>
        <div className="study-connection" aria-hidden="true"><span /><Sparkles size={24} /><span /></div>
        <div className="study-outputs">
          <div>
            <span className="output-symbol">?</span>
            <strong>Ask naturally</strong>
            <p>Document-based answers</p>
          </div>
          <div>
            <Check size={20} />
            <strong>Practise with AI</strong>
            <p>Generate · Attempt · Score</p>
          </div>
          <div>
            <Layers3 size={19} />
            <strong>Keep your progress</strong>
            <p>Persistent quiz history</p>
          </div>
        </div>
      </div>
      <div className="visual-caption">
        <span className="tiny-dot" /> ARCHITECTURE ILLUSTRATION · NOT A PRODUCT SCREENSHOT
      </div>
    </div>
  );
}

/** Shows the pizza ordering workflow explicitly as an illustration, not a screenshot. */
export function PizzaVisual() {
  return (
    <div
      className="pizza-visual visual-inner"
      aria-label="Illustrated natural-language ordering workflow, not a product screenshot"
    >
      <div className="illustration-heading">
        <span className="visual-brand"><WandSparkles size={18} /> AI Pizza Assistant</span>
        <span>LANGUAGE → ACTION</span>
      </div>
      <div className="pizza-composition">
        <div className="pizza-request">
          <span className="mono-label">01 / THE REQUEST</span>
          <blockquote>“I want a spicy chicken pizza with extra cheese”</blockquote>
          <div className="request-tags"><span>spicy</span><span>chicken</span><span>extra cheese</span></div>
        </div>
        <div className="pizza-divider" aria-hidden="true"><ArrowDown size={19} /></div>
        <div className="pizza-processing">
          <span><Sparkles size={15} /> Extract intent</span>
          <ArrowRight size={13} />
          <span><Search size={15} /> Match menu</span>
          <ArrowRight size={13} />
          <span><ShieldCheck size={15} /> Validate</span>
        </div>
        <div className="pizza-action">
          <span className="action-icon"><Check size={19} /></span>
          <div>
            <strong>From preference to a cart action.</strong>
            <span>With fallback parsing when AI needs a hand.</span>
          </div>
          <Code2 size={21} />
        </div>
      </div>
      <div className="visual-caption">
        <span className="tiny-dot" /> WORKFLOW ILLUSTRATION · NOT A PRODUCT SCREENSHOT
      </div>
    </div>
  );
}

const articles = [
  {
    id: 1,
    category: 'Technology',
    title: 'A closer look at the technology shaping our everyday lives',
    label: 'THE BIG PICTURE',
    art: 'technology',
  },
  {
    id: 2,
    category: 'Science',
    title: 'New perspectives on a world worth exploring',
    label: 'IDEAS & DISCOVERY',
    art: 'science',
  },
  {
    id: 3,
    category: 'Business',
    title: 'The conversations moving business forward',
    label: 'MARKETS & PEOPLE',
    art: 'business',
  },
];

/** Renders a labeled concept preview with optional local search and bookmarking. */
export function NewsVisual({ interactive = false }: Readonly<{ interactive?: boolean }>) {
  const [category, setCategory] = useState('For you');
  const [query, setQuery] = useState('');
  const [saved, setSaved] = useState<number[]>([]);
  const filtered = articles.filter(a => (
    category === 'For you' || (category === 'Saved' ? saved.includes(a.id) : a.category === category)
  ) && `${a.title} ${a.category}`.toLowerCase().includes(query.toLowerCase()));
  return (
    <div className={`news-visual visual-inner ${interactive ? 'is-interactive' : ''}`}>
      <div className="news-top">
        <span className="news-wordmark">the daily<span>.</span></span>
        <span className="news-concept">NEWSAPP / CONCEPT PREVIEW</span>
      </div>
      <div className="news-navigation">
        {['For you', 'Technology', 'Science', 'Business', 'Saved'].map(c => interactive ? (
          <button
            key={c}
            aria-pressed={category === c}
            onClick={() => setCategory(c)}
            className={category === c ? 'chosen' : ''}
          >
            {c}
          </button>
        ) : <span key={c} className={c === 'For you' ? 'chosen' : ''}>{c}</span>)}
      </div>
      <div className="news-title-row">
        <div>
          <span className="mono-label">A LITTLE CURIOSITY GOES A LONG WAY.</span>
          <h4>Your world. In focus.</h4>
        </div>
        {interactive ? (
          <label className="news-search">
            <Search size={15} />
            <input
              aria-label="Search concept stories"
              placeholder="Search stories"
              value={query}
              onChange={e => setQuery(e.target.value)}
            />
          </label>
        ) : <Search size={19} />}
      </div>
      <div className="news-articles">
        {filtered.map(a => (
          <article className="news-article" key={a.id}>
            <div className={`news-art ${a.art}`} aria-hidden="true"><i /><i /><i /></div>
            <div className="news-article-meta">
              <span>{a.category}</span>
              {interactive ? (
                <button
                  className="bookmark-button"
                  aria-label={`${saved.includes(a.id) ? 'Remove bookmark for' : 'Bookmark'} ${a.title}`}
                  aria-pressed={saved.includes(a.id)}
                  onClick={() => setSaved(prev => (
                    prev.includes(a.id) ? prev.filter(id => id !== a.id) : [...prev, a.id]
                  ))}
                >
                  <Bookmark size={14} fill={saved.includes(a.id) ? 'currentColor' : 'none'} />
                </button>
              ) : <Bookmark size={13} />}
            </div>
            <h5>{a.title}</h5>
            <span className="news-article-label">{a.label}</span>
          </article>
        ))}
      </div>
      {/* Preserve the previous paragraph's block layout so the existing empty-state spacing applies. */}
      {filtered.length === 0 && (
        <output className="news-empty" style={{ display: 'block' }}>
          {category === 'Saved'
            ? 'Bookmark a concept story to see it here.'
            : 'No concept stories match this search.'}
        </output>
      )}
      <div className="visual-caption">
        ILLUSTRATIVE CONTENT · NOT AN ORIGINAL APP SCREENSHOT{interactive && ' · INTERACTIVE DEMO'}
      </div>
    </div>
  );
}

/** Displays supplied screenshots unchanged, otherwise falling back to clearly labeled illustrations. */
export function ProjectVisual({ project, interactive = false }: Readonly<{
  project: Project;
  interactive?: boolean;
}>) {
  const image = project.screenshots[0];
  if (image) {
    return (
      <figure className="real-screenshot">
        <img src={image.src} alt={image.alt} loading="lazy" decoding="async" />
        <figcaption>{image.caption}</figcaption>
      </figure>
    );
  }
  if (project.id === 'studymate') {
    return <StudyVisual />;
  }
  if (project.id === 'pizzeria') {
    return <PizzaVisual />;
  }
  return <NewsVisual interactive={interactive} />;
}