// Generated by GitHub Copilot - Sep-30-2026
import { chromium } from '@playwright/test';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL || undefined });
try {
  const page = await browser.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 1 });
  await page.goto(pathToFileURL(resolve(root, 'public/social-card.svg')).href);
  await page.screenshot({ path: resolve(root, 'public/social-card.png') });
  // The uploaded resume is an original user asset and must never be regenerated.
  console.log('Generated social-card.png; the supplied resume remains unchanged.');
} finally { await browser.close(); }