// Generated by GitHub Copilot - Sep-30-2026
import { existsSync } from 'node:fs';
import { join } from 'node:path';

/** Maps visually inspected originals without changing their filenames or image content. */
export function suppliedAssets(directory) {
  /** Returns a public URL only when the original file exists. */
  const url = name => existsSync(join(directory, name)) ? `/assets/${encodeURIComponent(name)}` : null;
  /** Builds an accessible screenshot entry from an inspected source. */
  const image = (name, caption, theme = 'light') => ({ src: url(name), alt: caption, caption, theme });
  const prefix = 'WhatsApp Image 2026-09-29 at ';
  return {
    portrait: url('Media (2).jpg'),
    resume: url('shilpa_Gupta.pdf'),
    studymate: [
      image(`${prefix}19.08.33 (1).jpeg`, 'StudyMate.AI light dashboard with document upload, Q&A, quizzes, and learning history.'),
      image(`${prefix}19.08.55.jpeg`, 'StudyMate.AI dark dashboard with feature cards, quiz score analytics, and study workflow.', 'dark'),
      image(`${prefix}19.07.59 (2).jpeg`, 'AI Document Assistant displaying an uploaded PDF, a natural-language question, and its answer.'),
      image(`${prefix}19.07.59 (3).jpeg`, 'My Documents library with history, question, quiz, and delete actions for each PDF.'),
      image(`${prefix}19.07.59 (4).jpeg`, 'Document-based SQL quiz with multiple-choice answers and an attempt counter.'),
      image(`${prefix}19.07.59 (5).jpeg`, 'Saved document question and answer with an Ask New Question action.'),
      image(`${prefix}19.07.59 (6).jpeg`, 'Quiz Attempt History showing previous attempts and their scores.'),
      image(`${prefix}19.08.33.jpeg`, 'StudyMate document library containing SQL practice and Java interview PDFs.'),
    ].filter(item => item.src),
    pizzeria: [
      image(`${prefix}19.07.58 (2).jpeg`, 'Pizza Assistant adds a matching pizza and reports that the requested drink is unavailable.'),
      image(`${prefix}19.07.58 (5).jpeg`, 'Pizzeria landing page with ordering, pizza-building, and AI assistant entry points.'),
      image(`${prefix}19.07.58 (6).jpeg`, 'Pizza catalog with search, sorting, vegetarian and non-vegetarian filters, and a price limit.'),
      image('image.png', 'Smart Meal Builder accepts a meal description in plain language.'),
      image(`${prefix}19.07.58 (4).jpeg`, 'Meal Builder result with a selection of pizzas, quantities, and a calculated total.'),
      image(`${prefix}19.07.58 (1).jpeg`, 'Pizza Assistant interprets a spicy pizza request and prepares a cart action.'),
      image(`${prefix}19.07.59 (1).jpeg`, 'Pizzeria login with email, password, signup, and guest options.'),
      image(`${prefix}19.07.58.jpeg`, 'Signed-in Pizzeria home with ordering and pizza customization navigation.'),
      image(`${prefix}19.07.59.jpeg`, 'Pizza menu cards display images, dietary labels, ingredients, and prices.'),
      image(`${prefix}19.07.58 (3).jpeg`, 'Meal Builder form with a description field and Build My Meal action.'),
    ].filter(item => item.src),
  };
}