// Generated by GitHub Copilot - Sep-30-2026
import { lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { AnimatePresence, motion, useReducedMotion, useSpring } from 'motion/react';
import {
  ArrowDown,
  ArrowDownToLine,
  ArrowRight,
  ArrowUpRight,
  Award,
  Check,
  ChevronUp,
  ContactRound as Linkedin,
  Copy,
  GitFork as Github,
  GraduationCap,
  Mail,
  MapPin,
  Menu,
  Phone,
  Pause,
  Play,
  Sparkles,
  X,
} from 'lucide-react';
import { awards, experience, links, navigation, projects, type Project } from './data';
import { CareerTimeline, EngineeringCycle, MotionPausedContext, TechnologyEcosystem, useQuietMotion } from './components/EngineeringVisuals';
import { BrowserShowcase, ProjectStory } from './components/ProjectShowcase';
import HeroPortrait from './components/HeroPortrait';
import PageMotion from './components/PageMotion';
import AmbientBubbles from './components/AmbientBubbles';

const CaseStudy = lazy(() => import('./components/CaseStudy'));
const ContactDialog = lazy(() => import('./components/ContactDialog'));

/** Reveals content once while respecting reduced-motion preferences. */
export function Reveal({ children, className = '', delay = 0 }: Readonly<{
  children: ReactNode;
  className?: string;
  delay?: number;
}>) {
  const reduced = useQuietMotion();
  return (
    <motion.div
      className={`reveal-stage ${className}`}
      data-ambient="true"
      initial={reduced ? false : { opacity: 0, y: 30, scale: .985 }}
      whileInView={{ opacity: 1, y: 0, scale: 1 }}
      viewport={{ once: true, amount: .08 }}
      transition={{ duration: .65, delay, ease: [.22, 1, .36, 1] }}
    >
      {children}
    </motion.div>
  );
}

/** Renders a section title and its optional introduction. */
function SectionHeading({ number, eyebrow, title, description }: Readonly<{
  number: string;
  eyebrow: string;
  title: string;
  description?: string;
}>) {
  const quiet = useQuietMotion();
  return (
    <Reveal className="section-heading">
      <div>
        <p className="eyebrow"><span>{number} /</span> {eyebrow}</p>
        <h2 aria-label={title}>{title.split(' ').map((word, index) => <motion.span key={`${word}-${index}`} aria-hidden="true" initial={quiet ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .07, duration: .5 }}>{word}</motion.span>)}</h2>
      </div>
      {description && <p className="section-intro">{description}</p>}
    </Reveal>
  );
}

/** Adds mouse-only movement without changing keyboard or reduced-motion behavior. */
function MagneticLink({ children, href, className = '' }: Readonly<{
  children: ReactNode;
  href: string;
  className?: string;
}>) {
  const x = useSpring(0, { stiffness: 300, damping: 25 });
  const y = useSpring(0, { stiffness: 300, damping: 25 });
  const reduced = useQuietMotion();
  return (
    <motion.a
      href={href}
      className={className}
      style={{ x, y }}
      onPointerMove={e => {
        if (reduced || e.pointerType !== 'mouse') {
          return;
        }
        const rect = e.currentTarget.getBoundingClientRect();
        x.set((e.clientX - rect.left - rect.width / 2) * .075);
        y.set((e.clientY - rect.top - rect.height / 2) * .12);
      }}
      onPointerLeave={() => {
        x.set(0);
        y.set(0);
      }}
      onBlur={() => {
        x.set(0);
        y.set(0);
      }}
    >
      {children}
    </motion.a>
  );
}

/** Tracks the active section and preserves keyboard access to mobile navigation. */
function Navbar({ paused, onToggleMotion }: Readonly<{ paused: boolean; onToggleMotion: () => void }>) {
  const [active, setActive] = useState('home');
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);
  const menuButton = useRef<HTMLButtonElement>(null);
  const mobileMenu = useRef<HTMLElement>(null);
  const reduced = useReducedMotion();
  useEffect(() => {
    /** Selects the last navigation section that has crossed the active threshold. */
    const update = () => {
      setScrolled(window.scrollY > 20);
      const ids = Array.from(document.querySelectorAll<HTMLElement>('main section[id]')).map(section => section.id);
      ids.reverse();
      const selected = ids.find(id => (
        document.getElementById(id)?.getBoundingClientRect().top ?? Infinity
      ) <= 180);
      if (selected) {
        setActive(selected);
      }
    };
    let tick = 0;
    /** Coalesces scroll updates into a single animation frame. */
    const onScroll = () => {
      if (!tick) {
        tick = requestAnimationFrame(() => {
          update();
          tick = 0;
        });
      }
    };
    window.addEventListener('scroll', onScroll, { passive: true });
    update();
    /** Closes the mobile navigation when switching to the desktop layout. */
    const resize = () => {
      if (window.innerWidth > 1000) {
        setOpen(false);
      }
    };
    window.addEventListener('resize', resize);
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', resize);
      cancelAnimationFrame(tick);
    };
  }, []);
  useEffect(() => {
    if (!open) {
      return;
    }
    /** Restores focus to the menu toggle when Escape dismisses navigation. */
    const escape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setOpen(false);
        menuButton.current?.focus();
      }
    };
    /** Dismisses navigation only for pointer events outside the menu and toggle. */
    const outside = (e: PointerEvent) => {
      if (
        !mobileMenu.current?.contains(e.target as Node)
        && !menuButton.current?.contains(e.target as Node)
      ) {
        setOpen(false);
      }
    };
    window.addEventListener('keydown', escape);
    window.addEventListener('pointerdown', outside);
    return () => {
      window.removeEventListener('keydown', escape);
      window.removeEventListener('pointerdown', outside);
    };
  }, [open]);
  return (
    <header className={`site-header ${scrolled ? 'is-scrolled' : ''}`}>
      <div className="nav-shell">
        <a href="#home" className="brand" aria-label="Shilpa Gupta home">
          shilpa<span>.</span><span className="brand-last">gupta</span>
        </a>
        <nav className="desktop-nav" aria-label="Main navigation">
          {navigation.map(n => (
            <a
              key={n.id}
              href={`#${n.id}`}
              aria-current={active === n.id ? 'location' : undefined}
            >
              {n.label}
            </a>
          ))}
        </nav>
        <a className="nav-contact" href="#contact">
          Let’s talk <ArrowUpRight size={16} />
        </a>
        <button className="motion-toggle icon-button" aria-label={paused ? 'Play ambient animations' : 'Pause ambient animations'} aria-pressed={paused} onClick={onToggleMotion} disabled={!!reduced} title={reduced ? 'Reduced motion is enabled on your device' : 'Control ambient animation'}>
          {paused || reduced ? <Play size={17} /> : <Pause size={17} />}
        </button>
        <button
          ref={menuButton}
          className="menu-toggle icon-button"
          aria-label={open ? 'Close navigation' : 'Open navigation'}
          aria-expanded={open}
          aria-controls="mobile-navigation"
          onClick={() => setOpen(!open)}
        >
          {open ? <X /> : <Menu />}
        </button>
      </div>
      <AnimatePresence>
        {open && (
          <motion.nav
            ref={mobileMenu}
            id="mobile-navigation"
            className="mobile-nav"
            aria-label="Mobile navigation"
            initial={{ opacity: 0, y: reduced ? 0 : -8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: reduced ? 0 : -8 }}
          >
            {navigation.map((n, i) => (
              <a
                href={`#${n.id}`}
                key={n.id}
                aria-current={active === n.id ? 'location' : undefined}
                onClick={() => {
                  setOpen(false);
                  document.getElementById(n.id)?.focus({ preventScroll: true });
                }}
              >
                <span>{String(i + 1).padStart(2, '0')}</span>{n.label}<ArrowUpRight size={17} />
              </a>
            ))}
          </motion.nav>
        )}
      </AnimatePresence>
    </header>
  );
}

/** Displays project details and entry points to its case study and external links. */
function ProjectCard({ project, onSelect }: Readonly<{
  project: Project;
  onSelect: (project: Project) => void;
}>) {
  const reduced = useQuietMotion();
  return (
    <Reveal>
      <motion.article
        className={`project-card project-${project.id}`}
        data-ambient="true"
        whileHover={reduced ? undefined : { y: -4 }}
        transition={{ duration: .25 }}
      >
        <div className="project-visual-wrap">
          <BrowserShowcase project={project} onOpen={() => onSelect(project)} />
          <button
            className="visual-open"
            onClick={() => onSelect(project)}
            aria-label={`Open ${project.name} case study`}
          >
            <ArrowUpRight size={21} />
          </button>
        </div>
        <div className="project-content">
          <div className="project-topline">
            <span className="mono-label">{project.category}</span>
            <span className="project-number">/{project.number}</span>
          </div>
          <h3>{project.name}</h3>
          <p className="project-tagline">{project.tagline}</p>
          <p className="project-description">{project.description}</p>
          <div className="chip-list project-stack">
            {project.stack.map(s => <span className="chip" key={s}>{s}</span>)}
          </div>
          <ul className="project-highlights">
            {project.highlights.map(h => <li key={h}><Check size={14} />{h}</li>)}
          </ul>
          <div className="project-actions">
            <button className="text-link" onClick={() => onSelect(project)}>
              View case study <ArrowUpRight size={17} />
            </button>
            {project.live && (
              <a className="subtle-link" href={project.live} target="_blank" rel="noreferrer">
                Live demo <ArrowUpRight size={15} />
              </a>
            )}
            {project.github && (
              <a
                className="project-source"
                href={project.github}
                target="_blank"
                rel="noreferrer"
                aria-label={`${project.name} source code on GitHub`}
              >
                <Github size={14} /> GitHub
              </a>
            )}
          </div>
        </div>
        <ProjectStory project={project} />
      </motion.article>
    </Reveal>
  );
}

// Generated by GitHub Copilot - Sep-30-2026
/** Keeps the success message ahead of the failure fallback, matching copy state priority. */
function getCopyStatus(copied: boolean, copyFailed: boolean): string {
  if (copied) {
    return 'Email copied to clipboard.';
  }
  if (copyFailed) {
    return 'Please select the email address to copy it.';
  }
  return '';
}

/** Provides contact links and an accessible clipboard result announcement. */
function Contact() {
  const [messageOpen, setMessageOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [copyFailed, setCopyFailed] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(() => () => clearTimeout(timer.current), []);
  /** Copies the public email address and clears the success state after a short delay. */
  const copy = async () => {
    try {
      await navigator.clipboard.writeText('shilpakalwar25@gmail.com');
      setCopied(true);
      setCopyFailed(false);
      clearTimeout(timer.current);
      timer.current = setTimeout(() => setCopied(false), 2500);
    } catch {
      setCopyFailed(true);
    }
  };
  return (
    <section className="contact-section section" id="contact" tabIndex={-1} data-ambient="true">
      <div className="container">
        <Reveal>
          <p className="eyebrow"><span>08 /</span> START A CONVERSATION</p>
          <h2 className="contact-title">Contact Me</h2>
          <div className="contact-heading">
            <h3>Good things start<br />with a <span>hello.</span></h3>
            <MagneticLink href={links.email} className="contact-arrow">
              <ArrowUpRight size={44} />
              <span className="sr-only">Email Shilpa Gupta</span>
            </MagneticLink>
          </div>
          <div className="contact-invitation">
            <div><h3>Let’s talk about your opportunity.</h3><p>Recruiters and hiring teams: introduce yourself and leave a message.</p></div>
            <button className="button button-primary message-trigger" onClick={() => setMessageOpen(true)}>Talk to me <Mail size={18} /></button>
          </div>
          <div className="contact-bottom contact-network" data-ambient="true">
            <span className="contact-network-orbit" aria-hidden="true" />
            <div className="contact-primary">
              <span className="contact-label"><span className="contact-status-dot" />DIRECT CONTACT</span>
              <div className="email-row">
                <a href={links.email}>shilpakalwar25@gmail.com</a>
                <button className="icon-button copy-button" onClick={copy} aria-label="Copy email address">
                  {copied ? <Check size={17} /> : <Copy size={17} />}
                </button>
              </div>
              <output className="copy-status">{getCopyStatus(copied, copyFailed)}</output>
              <div className="contact-meta">
                <span><MapPin size={15} /> Bangalore, India</span>
                <a href={links.phone}><Phone size={15} /> +91 7338683445</a>
              </div>
            </div>
            <div className="contact-links">
              <a className="contact-network-link" href={links.linkedin} target="_blank" rel="noreferrer">
                <span>LinkedIn</span> <ArrowUpRight size={16} />
              </a>
              <a className="contact-network-link" href={links.github} target="_blank" rel="noreferrer">
                <span>GitHub</span> <ArrowUpRight size={16} />
              </a>
              <a className="contact-network-link" href={links.leetcode} target="_blank" rel="noreferrer">
                <span>LeetCode</span> <ArrowUpRight size={16} />
              </a>
              <a className="contact-network-link" href={links.resumeDownload} download>
                <span>Download resume</span> <ArrowDownToLine size={16} />
              </a>
            </div>
          </div>
        </Reveal>
      </div>
      <Suspense fallback={messageOpen ? <output className="case-loading">Opening message composer…</output> : null}>
        {messageOpen && <ContactDialog onClose={() => setMessageOpen(false)} />}
      </Suspense>
    </section>
  );
}

/** Renders the portfolio and lazily opens the selected project's native dialog. */
export default function App() {
  const [selected, setSelected] = useState<Project | null>(null);
  const [paused, setPaused] = useState(false);
  const [hidden, setHidden] = useState(false);
  const reduced = useReducedMotion();
  useEffect(() => {
    /** Gates all ambient regions, including lazy dialogs, instead of animating offscreen. */
    const observer = new IntersectionObserver(entries => {
      for (const entry of entries) {
        (entry.target as HTMLElement).dataset.visible = String(entry.isIntersecting);
      }
    });
    /** Watches newly mounted lazy-dialog regions without polling the DOM. */
    const observed = new WeakSet<Element>();
    const observeRegions = () => document.querySelectorAll('.portrait-stage, .technology-ribbon, [data-ambient]').forEach(element => {
      if (!observed.has(element)) { observed.add(element); observer.observe(element); }
    });
    observeRegions();
    const additions = new MutationObserver(observeRegions);
    additions.observe(document.getElementById('root')!, { childList: true, subtree: true });
    /** Suspends CSS and WebGL animation while the tab is hidden. */
    const visibility = () => setHidden(document.hidden);
    document.addEventListener('visibilitychange', visibility);
    visibility();
    return () => { observer.disconnect(); additions.disconnect(); document.removeEventListener('visibilitychange', visibility); };
  }, []);
  return (
    <MotionPausedContext.Provider value={paused || hidden || !!reduced}>
    <div className="portfolio-shell" data-motion={paused || hidden || reduced ? 'paused' : 'playing'}>
      <AmbientBubbles />
      <PageMotion />
      <Navbar paused={paused} onToggleMotion={() => setPaused(value => !value)} />
      <main id="main">
        <section className="hero container" id="home" tabIndex={-1} data-ambient="true">
          <div className="hero-copy">
            <motion.p
              className="hero-kicker"
              initial={reduced ? false : { opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: .6 }}
            >
              <span className="tiny-dot" /> SOFTWARE ENGINEER | FULL-STACK DEVELOPER
            </motion.p>
            <motion.h2
              initial={reduced ? false : { opacity: 0, y: 22 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: .1, duration: .8 }}
            >
              <span className="hero-greeting">Hi, I’m Shilpa Gupta.</span><br/>
              Engineering<br />
              <motion.span className="hero-emphasis" initial={reduced ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35, duration: .7 }}>at the intersection of</motion.span><br />
              frontend, backend, and scalable architecture.
            </motion.h2>
            <motion.div
              initial={reduced ? false : { opacity: 0, y: 18 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: .22, duration: .7 }}
            >
              <p className="hero-role">Software Engineer | Full-Stack Developer</p>
              <p className="hero-description">
                Engineering at Accenture. Building across Angular, Java / Spring Boot,
                and Node.js—from the first interaction to the data behind it.
              </p>
              <div className="hero-actions">
                <MagneticLink href="#projects" className="button button-primary">
                  Explore my work <ArrowUpRight size={18} />
                </MagneticLink>
                <a className="button button-secondary" href={links.resume} target="_blank" rel="noreferrer">
                  View resume <ArrowDownToLine size={16} />
                </a>
              </div>
              <div className="hero-socials">
                <a href={links.github} target="_blank" rel="noreferrer">
                  <Github size={16} />GitHub<ArrowUpRight size={13} />
                </a>
                <a href={links.linkedin} target="_blank" rel="noreferrer">
                  <Linkedin size={16} />LinkedIn<ArrowUpRight size={13} />
                </a>
                <a href="#contact"><Mail size={16} />Contact me</a>
              </div>
            </motion.div>
          </div>
          <HeroPortrait paused={paused || hidden} />
          <div className="hero-footer">
            <div>
              <span className="hero-footer-label">CURRENTLY BUILDING AT</span>
              <strong>Accenture <ArrowUpRight size={14} /></strong>
            </div>
            <p>Frontend precision.<br />Full-stack perspective.</p>
            <a href="#about" className="scroll-cue">SCROLL TO EXPLORE <ArrowDown size={15} /></a>
          </div>
        </section>

        <section className="about-section section" id="about" tabIndex={-1}>
          <div className="container">
            <SectionHeading
              number="01"
              eyebrow="THE PERSON BEHIND THE CODE"
              title="About Me"
            />
            <div className="about-grid">
              <Reveal>
                <p className="body-lead">
                  I’m Shilpa, a Software Engineer working on enterprise web applications at Accenture
                  with completed full-stack projects in learning, ordering, and news discovery.
                </p>
                <p>
                  My frontend work centres on Angular, TypeScript, RxJS, NgRx, and Micro Frontend architecture.
                  I connect those interfaces to Java / Spring Boot and Node.js / Express.js APIs,
                  backed by MySQL and MongoDB.
                </p>
                <a href="#experience" className="text-link about-link">
                  More about my experience <ArrowRight size={17} />
                </a>
              </Reveal>
              <Reveal delay={.1}><EngineeringCycle /></Reveal>
            </div>
          </div>
        </section>

        <section className="experience-section section" id="experience" tabIndex={-1}>
          <div className="container">
            <SectionHeading
              number="02"
              eyebrow="PROFESSIONAL EXPERIENCE"
              title="Experience"
              description="From assessment workflows to enterprise applications, learning through the work that ships."
            />
            <CareerTimeline>
              {experience.map((role, i) => (
                <Reveal className="timeline-item" key={role.company} delay={i * .08}>
                  <div className="timeline-date">
                    <span className={`timeline-node ${role.current ? 'current' : ''}`} />
                    <span>{role.period}</span>
                    <small>{role.current ? 'CURRENT ROLE' : 'INTERNSHIP'}</small>
                  </div>
                  <div className="experience-card">
                    <div className="experience-title">
                      <div>
                        <h3>{role.company}</h3>
                        <p>{role.role} {role.current && <span className="role-short">(PADA)</span>}</p>
                      </div>
                      <span className="company-monogram" aria-hidden="true">
                        {role.current ? 'ac>' : 'fi.'}
                      </span>
                    </div>
                    <h4>{role.intro}</h4>
                    <ul>{role.bullets.map(b => <li key={b}>{b}</li>)}</ul>
                    <div className="chip-list">
                      {role.stack.map(s => <span className="chip" key={s}>{s}</span>)}
                    </div>
                  </div>
                </Reveal>
              ))}
            </CareerTimeline>
          </div>
        </section>

        <FeaturedWork onSelect={setSelected} />

        <section className="skills-section section container" id="skills" tabIndex={-1}>
          <SectionHeading number="04" eyebrow="TECHNICAL TOOLKIT" title="Skills" description="Explore the technologies across my application stack." />
          <div className="technology-ribbon" aria-label="Core technologies" data-ambient="true">
            <div className="ribbon-track">
              {[false, true].map(duplicate => <div className="ribbon-set" key={String(duplicate)} aria-hidden={duplicate}>{['Angular', 'TypeScript', 'Java / Spring Boot', 'Node.js', 'C# / .NET', 'Micro Frontend'].map(text => <span key={text}><Sparkles size={18} aria-hidden="true" />{text}</span>)}</div>)}
            </div>
          </div>
          <TechnologyEcosystem />
        </section>

        <section className="education-section section container" id="education" tabIndex={-1} aria-labelledby="education-heading" data-ambient="true">
          <Reveal>
            <p className="eyebrow"><span>05 /</span> FOUNDATIONS & CONTINUED LEARNING</p>
            <div className="learning-row">
              <div className="education-block">
                <GraduationCap size={26} strokeWidth={1.4} />
                <h2 id="education-heading">Education</h2>
                <h3>JSS Academy of Technical Education</h3>
                <p>Bangalore · B.E. Computer Science</p>
                <div className="education-meta">
                  <span>2020 — 2024</span>
                  <span>CGPA: 8.6</span>
                </div>
              </div>
              <div className="certifications certification-panel" id="certifications" tabIndex={-1} aria-labelledby="certifications-heading">
                <div className="certification-heading">
                  <p className="eyebrow"><span>06 /</span> CONTINUED LEARNING</p>
                  <h2 id="certifications-heading">Certifications</h2>
                </div>
                <div className="certification-grid">
                {[
                  { title: 'Microsoft GitHub Copilot Certification', source: '2024' },
                  { title: 'Data Structures', source: 'HackerRank' },
                  { title: 'The Web Developer Bootcamp', source: 'Colt Steele · 2023' },
                ].map((c, i) => (
                  <Reveal className="certification" key={c.title} delay={i * .07}>
                    <span>0{i + 1}</span>
                    <div>
                      <h3>{c.title}</h3>
                      <p>{c.source}</p>
                    </div>
                    <Award size={18} />
                  </Reveal>
                ))}
                </div>
              </div>
            </div>
          </Reveal>
        </section>

        <section className="achievements-section section" id="achievements" tabIndex={-1}>
          <div className="container">
            <SectionHeading number="07" eyebrow="MILESTONES" title="Recognition & Awards" />
            <div className="awards-grid" data-ambient="true">
              {awards.map((award, i) => (
                <Reveal className="award-card" key={award.title} delay={i * .08}>
                  <div className="award-top"><Award size={29} strokeWidth={1.2} /><span>{award.date}</span></div>
                  <span className="mono-label">{award.tag}</span>
                  <h3>{award.title}</h3><p>{award.subtitle}</p>
                </Reveal>
              ))}
            </div>
          </div>
        </section>
        <Contact />
      </main>
      <footer className="site-footer container">
        <a className="brand" href="#home">
          shilpa<span>.</span><span className="brand-last">gupta</span>
        </a>
        <p>© {new Date().getFullYear()} Shilpa Gupta. Crafted with intent.</p>
        <a href="#home" className="back-top">Back to top <ChevronUp size={15} /></a>
      </footer>
      <Suspense fallback={selected ? <output className="case-loading">Opening case study…</output> : null}>
        {selected && <CaseStudy project={selected} onClose={() => setSelected(null)} />}
      </Suspense>
    </div>
    </MotionPausedContext.Provider>
  );
}

// Generated by GitHub Copilot - Sep-30-2026
/** Presents the completed projects after professional experience. */
function FeaturedWork({ onSelect }: Readonly<{ onSelect: (project: Project) => void }>) {
  return (
    <section className="projects-section section container" id="projects" tabIndex={-1}>
      <SectionHeading number="03" eyebrow="SELECTED WORK / INTERACTIVE ENGINEERING" title="Projects" description="Explore the original screens, workflows, and engineering behind my completed projects." />
      <div className="project-list">
        {projects.map(project => <ProjectCard project={project} key={project.id} onSelect={onSelect} />)}
      </div>
    </section>
  );
}

