// Generated by GitHub Copilot - Sep-30-2026
import { uploadedMedia } from './media';

export type Screenshot = { src: string; alt: string; caption: string };
export type Flow = { title: string; steps: string[] };
export type Project = {
  id: string;
  number: string;
  name: string;
  category: string;
  tagline: string;
  description: string;
  stack: string[];
  features: string[];
  highlights: string[];
  live?: string;
  github?: string;
  screenshots: Screenshot[];
  problem: string;
  solution: string;
  architecture: string;
  flows: Flow[];
  challenges: { title: string; body: string }[];
  implementation: string[];
  optimization: string;
  deployment: string;
};

export const links = {
  github: 'https://github.com/Shilpa2504',
  linkedin: 'https://www.linkedin.com/in/shilpa-gupta-621a90259/',
  email: 'mailto:shilpakalwar25@gmail.com',
  phone: 'tel:+917338683445',
  leetcode: 'https://leetcode.com/Shilpa_gupta/',
  reference: 'https://myportfolio-d378f.firebaseapp.com/',
  resume: uploadedMedia.resume ?? '/resume.html',
  resumeDownload: uploadedMedia.resume ?? '/Shilpa-Gupta-Resume.pdf',
};

export const navigation = [
  { id: 'home', label: 'Home' }, { id: 'about', label: 'About Me' },
  { id: 'experience', label: 'Experience' }, { id: 'projects', label: 'Projects' },
  { id: 'skills', label: 'Skills' }, { id: 'education', label: 'Education' },
  { id: 'certifications', label: 'Certifications' },
  { id: 'achievements', label: 'Recognition & Awards' }, { id: 'contact', label: 'Contact' },
];

export const skills = [
  { name: 'Frontend', note: 'Interfaces with intent', items: ['Angular', 'TypeScript', 'JavaScript', 'HTML5', 'CSS3', 'Bootstrap', 'RxJS', 'NgRx'] },
  { name: 'Backend', note: 'From request to response', items: ['Java', 'Spring Boot', 'Node.js', 'Express.js', 'C#', '.NET', 'REST APIs'] },
  { name: 'Database', note: 'Structured to persist', items: ['MySQL', 'MongoDB', 'JPA/Hibernate'] },
  { name: 'Architecture', note: 'Built to work together', items: ['Micro Frontend', 'Microservices', 'State Management', 'Dependency Injection', 'Lazy Loading'] },
  { name: 'Testing', note: 'Confidence in every change', items: ['Jasmine', 'Karma'] },
  { name: 'Tools', note: 'The everyday toolkit', items: ['Git', 'GitHub', 'npm', 'VS Code', 'Visual Studio', 'Linux/Unix'] },
  { name: 'Delivery', note: 'From collaboration to release', items: ['Agile/Scrum', 'Debugging', 'Production Support', 'GitHub Copilot'] },
];

// Add supplied screenshots here in their original order. Images are rendered unchanged
// with object-fit: contain. Do not relabel the architecture illustrations as screenshots.
export const projects: Project[] = [
  {
    id: 'studymate', number: '01', name: 'StudyMate.AI',
    category: 'LEARNING PLATFORM / FULL STACK',
    tagline: 'Turn documents into understanding.',
    description: 'A study platform connecting document Q&A, generated quizzes, and persistent learning history.',
    stack: ['Angular', 'Spring Boot', 'MySQL', 'JPA/Hibernate', 'JWT', 'Spring Security'],
    features: ['PDF upload & natural-language Q&A', 'Generated quizzes & automated scoring', 'Attempt tracking & persistent quiz history', 'SHA-256 duplicate upload detection', 'JWT authentication & role-based access', 'Light / dark dashboard & quiz score analytics'],
    highlights: ['Document intelligence', 'Secure REST APIs', 'Persistent learning workflows'],
    live: 'https://study-mate-ai-six.vercel.app/',
    github: 'https://github.com/Shilpa2504/StudyMate.AI',
    screenshots: uploadedMedia.studymate,
    problem: 'Finding an explanation inside a long study document takes time. Turning that material into practice questions adds another manual step.',
    solution: 'A connected study workflow: upload a PDF, ask questions in natural language, then practise with document-based quizzes and revisit previous attempts.',
    architecture: 'Angular handles document interactions, route guards, and HTTP interceptors. Spring Boot exposes REST APIs secured with JWT and Spring Security, coordinating document Q&A and quiz generation. JPA/Hibernate persists application data in MySQL.',
    flows: [
      { title: 'Ask your document', steps: ['PDF upload', 'Document / session processing', 'Natural-language question', 'Question processing', 'Generated response', 'Angular UI'] },
      { title: 'Learn through practice', steps: ['Document', 'Generated questions', 'User attempt', 'Automated scoring', 'Quiz history in MySQL'] },
      { title: 'Application architecture', steps: ['Angular + guards / interceptors', 'JWT + Spring Security', 'Spring Boot REST APIs', 'JPA / Hibernate', 'MySQL'] },
    ],
    challenges: [
      { title: 'Repeated document uploads', body: 'Client-side SHA-256 hashing supports duplicate detection before repeating an upload workflow.' },
      { title: 'Protecting user workflows', body: 'JWT authentication, backend role-based access, route guards, and HTTP interceptors connect the frontend session with secured APIs.' },
      { title: 'Keeping practice connected', body: 'Quiz scoring, attempt tracking, and persisted history let users return to their previous work rather than treating each quiz as a one-off session.' },
    ],
    implementation: ['Document upload and question interactions in Angular.', 'Spring Boot endpoints coordinate document sessions and question requests.', 'Generated quizzes move through an attempt, scoring, and history-persistence workflow.', 'MySQL and JPA/Hibernate support persisted application state.'],
    optimization: 'SHA-256 client-side hashing targets duplicate uploads. The focus is avoiding repeated work, not claiming unmeasured speed improvements.',
    deployment: 'The live frontend is available on Vercel. The frontend communicates with the Spring Boot backend through REST APIs.',
  },
  {
    id: 'pizzeria', number: '02', name: 'AI-Powered Pizzeria',
    category: 'CONVERSATIONAL ORDERING / MEAN STACK',
    tagline: 'From a conversation to a cart.',
    description: 'Natural-language ordering meets a customizable meal builder, with menu matching and a validated cart workflow.',
    stack: ['Angular', 'Node.js', 'Express.js', 'MongoDB', 'MongoDB Atlas', 'Vercel', 'Render'],
    features: ['AI Pizza Assistant', 'Natural-language ordering & menu matching', 'Ingredient understanding & order validation', 'Intent processing with fallback parsing', 'Natural-language Smart Meal Builder', 'Pizza customization & real-time pricing', 'Menu search, sorting, type & price filters', 'Customized combinations & cart actions'],
    highlights: ['Intent → action', 'Menu-aware validation', 'Resilient fallback parsing'],
    live: 'https://pizzeria-ashen-alpha.vercel.app/',
    github: 'https://github.com/Shilpa2504/Pizzeria',
    screenshots: uploadedMedia.pizzeria,
    problem: 'Ordering a customized pizza means translating a personal preference into menu choices, ingredient selections, and a valid cart item.',
    solution: 'A conversational assistant interprets a natural-language request and connects it to the menu. A Smart Meal Builder gives users a direct way to select ingredients, customize combinations, and see the price change.',
    architecture: 'Angular provides the ordering interface. Node.js and Express.js expose the application endpoints. The assistant processes ordering requests, while menu matching and validation turn that interpretation into a structured cart action. MongoDB, hosted on Atlas, provides persistence.',
    flows: [
      { title: 'AI Pizza Assistant', steps: ['Natural-language request', 'Intent extraction', 'Menu + ingredient matching', 'Availability validation', 'Fallback parser if needed', 'Cart / order action'] },
      { title: 'Request to interaction', steps: ['Angular frontend', 'Ordering API endpoint', 'Intent processing', 'Structured ordering result', 'Cart workflow'] },
      { title: 'Full-stack foundation', steps: ['Angular · Vercel', 'Node.js / Express.js · Render', 'MongoDB · hosted on Atlas'] },
      { title: 'Smart Meal Builder', steps: ['Ingredient selection', 'Customized composition', 'Real-time price calculation', 'Personalized meal combination'] },
    ],
    challenges: [
      { title: 'Language is not a menu ID', body: 'Intent extraction and menu matching translate a conversational request into a concrete item rather than treating an unvalidated response as an order.' },
      { title: 'Responses can be incomplete', body: 'Fallback parsing supports the ordering flow when assistant processing is unavailable or incomplete. Validation checks the request before preparing cart actions.' },
      { title: 'Customization affects price', body: 'The Smart Meal Builder connects dynamic ingredient selections with real-time price calculation and customized meal composition.' },
    ],
    implementation: ['Process conversational requests through the ordering API endpoint.', 'Match extracted intent and ingredients to available menu choices.', 'Validate the result and use fallback parsing where required.', 'Prepare structured cart actions and update the ordering workflow.'],
    optimization: 'Fallback parsing handles unavailable processing and incomplete responses. The meal builder updates pricing as ingredients change; no latency or throughput measurements are claimed.',
    deployment: 'Angular frontend on Vercel; Node.js / Express.js backend on Render; MongoDB persistence on MongoDB Atlas.',
  },
  {
    id: 'newsapp', number: '03', name: 'NewsApp',
    category: 'CONTENT DISCOVERY / MEAN STACK',
    tagline: 'A more personal way to stay informed.',
    description: 'A news aggregation platform bringing category discovery, search, preferences, and bookmarks into one responsive experience.',
    stack: ['Angular', 'MongoDB', 'Express.js', 'Node.js', 'REST APIs'],
    features: ['External REST API news aggregation', 'Category-based discovery & search', 'Dynamic Angular routing', 'User preferences & bookmarking', 'MongoDB-backed persistence', 'Responsive, personalized browsing'],
    highlights: ['API-driven discovery', 'Personalized browsing', 'Saved content'],
    screenshots: [],
    problem: 'News arrives across sources and categories. Finding relevant stories and returning to saved content needs a more focused browsing workflow.',
    solution: 'An Angular news experience that brings external news APIs together with category navigation, search, preferences, and persistent bookmarks.',
    architecture: 'Angular manages responsive presentation and dynamic navigation. Node.js and Express.js provide the backend layer and external REST API integration. MongoDB stores user preferences and bookmarked content.',
    flows: [
      { title: 'Content discovery', steps: ['External news REST APIs', 'Node.js / Express.js', 'Angular category + search views', 'Personalized browsing'] },
      { title: 'Make it yours', steps: ['Preferences / bookmarks', 'Application REST APIs', 'MongoDB persistence', 'Return to saved content'] },
    ],
    challenges: [
      { title: 'Discover without losing context', body: 'Categories, search, and dynamic Angular routing organize browsing around a user’s interests.' },
      { title: 'Personalization that persists', body: 'MongoDB-backed preferences and bookmarks connect discovery with the ability to return to selected content.' },
    ],
    implementation: ['Aggregate content from external REST APIs.', 'Organize news through category navigation and search.', 'Use dynamic Angular routing for browsing views.', 'Persist user preferences and bookmarks in MongoDB.'],
    optimization: 'Responsive presentation supports browsing across screen sizes. No measured performance results or additional optimization techniques were supplied.',
    deployment: 'A public deployment link has not been supplied. The visual shown here is an illustrative concept preview, not a screenshot of the original application.',
  },
];

export const experience = [
  {
    company: 'Accenture', role: 'Packaged App Development Associate', short: 'PADA', period: 'Nov 2024 — Present', current: true,
    intro: 'Enterprise frontend engineering, connected to the full stack.',
    bullets: ['Maintained Angular Micro Frontend applications on MyISP across business workflow modules.', 'Built with reusable UI components, RxJS, NgRx, and Angular Signals; contributed to Angular modernization and migration.', 'Integrated RESTful microservices and Java / Spring Boot backend services.', 'Applied lazy loading and dependency injection; tested with Jasmine and Karma.', 'Supported debugging, defect resolution, Agile/Scrum sprint delivery, and production deployments.', 'Used GitHub Copilot and AIDC Pack in the development workflow.'],
    stack: ['Angular 21', 'TypeScript', 'Micro Frontend', 'Java', 'Spring Boot', 'Jasmine / Karma'],
  },
  {
    company: 'FindInbox Limited', role: 'Web Developer Intern', short: 'Internship', period: 'Nov 2023 — Jan 2024', current: false,
    intro: 'Building useful interfaces for assessment and analytics.',
    bullets: ['Worked on Angular web applications, REST API integration, and state management.', 'Contributed to assessment workflows and analytics dashboards.', 'Worked on performance and usability improvements.'],
    stack: ['Angular', 'REST APIs', 'State Management', 'Web Development'],
  },
];

export const awards = [
  { title: 'Star of the Month', subtitle: 'Accenture', date: 'February 2026', tag: 'RECOGNITION' },
  { title: 'TechWeek Stars', subtitle: 'Wall of Fame · Accenture', date: 'December 2025', tag: 'WALL OF FAME' },
  { title: 'Tech Expressway Program', subtitle: 'Stream Training Excellence · Accenture', date: 'December 2025', tag: 'TRAINING EXCELLENCE' },
];