// Generated by GitHub Copilot - Sep-30-2026
type UploadedScreenshot = { src: string; alt: string; caption: string };
type UploadedMedia = {
  portrait: string | null;
  resume: string | null;
  studymate: UploadedScreenshot[];
  pizzeria: UploadedScreenshot[];
};

declare const __PORTFOLIO_MEDIA__: UploadedMedia;

/** Build-time discovery includes only real files and never manufactures missing screenshots. */
export const uploadedMedia: UploadedMedia = __PORTFOLIO_MEDIA__;

/** Only point to files actually supplied; no generated portrait substitutes. */
export const portrait: { src: string | null; alt: string } = {
  src: uploadedMedia.portrait,
  alt: 'Shilpa Gupta seated outdoors in a garden',
};