// Generated by GitHub Copilot - Sep-30-2026
import { createHash } from 'node:crypto';
import { recruiterEmail } from '../server/email-template.mjs';

const recipient = 'shilpakalwar25@gmail.com';
/** Checks bounded email structure in linear time, excluding header and markup characters. */
function validEmail(value) {
  if (typeof value !== 'string' || value.length > 254 || /[\s<>]/.test(value)) return false;
  const parts = value.split('@');
  if (parts.length !== 2 || !parts[0] || !parts[1]) return false;
  const labels = parts[1].split('.');
  return labels.length >= 2 && labels.every(label => label.length > 0);
}

/** Validates bounded text, email headers, consent, and single-use bot verification input. */
export function validateMessage(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) return null;
  const limits = { name: 100, email: 254, company: 120, message: 4000, token: 2048, requestId: 36, website: 200 };
  const values = {};
  for (const [key, limit] of Object.entries(limits)) {
    if (typeof input[key] !== 'string' || input[key].length > limit) return null;
    values[key] = input[key].trim();
  }
    if (!values.name || values.message.length < 10 || !validEmail(values.email)
      || /[\x00-\x1f\x7f]/.test(values.name + values.email + values.company)
      || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(values.message)
      || !values.token || values.website || input.consent !== true
      || !/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(values.requestId)) return null;
  return values;
}

/** Resolves only server-side mail credentials and an explicitly allowed HTTPS site origin. */
function configuration(env) {
  try {
    const site = new URL(env.CONTACT_ORIGIN);
    if (site.protocol !== 'https:' || site.origin !== env.CONTACT_ORIGIN || site.username || site.password
      || !env.RESEND_API_KEY || !env.TURNSTILE_SECRET_KEY || !env.TURNSTILE_SITE_KEY
      || !validEmail(env.CONTACT_FROM || '')) return null;
    return { origin: site.origin, hostname: site.hostname, key: env.RESEND_API_KEY, from: env.CONTACT_FROM,
      secret: env.TURNSTILE_SECRET_KEY, siteKey: env.TURNSTILE_SITE_KEY };
  } catch { return null; }
}

/** Creates a testable handler; never accepts a destination or email subject from the browser. */
export function createContactHandler({ env = process.env, fetcher = fetch } = {}) {
  /** Verifies origin, payload, and bot protection before requesting a single fixed-recipient email. */
  return async function contact(req, res) {
    res.setHeader('Cache-Control', 'no-store');
    res.setHeader('X-Content-Type-Options', 'nosniff');
    res.setHeader('Content-Security-Policy', "default-src 'none'; frame-ancestors 'none'");
    res.setHeader('Referrer-Policy', 'no-referrer');
    const settings = configuration(env);
    if (req.method === 'GET') return res.status(200).json({ available: !!settings, siteKey: settings?.siteKey || '' });
    if (req.method !== 'POST') { res.setHeader('Allow', 'GET, POST'); return res.status(405).json({ error: 'Method not allowed.' }); }
    if (!settings) return res.status(503).json({ error: 'Direct sending is not configured. Please use the email link.' });
    if (req.headers.origin !== settings.origin) return res.status(403).json({ error: 'Request not allowed.' });
    if (!/^application\/json(?:;|$)/i.test(req.headers['content-type'] || '')) return res.status(415).json({ error: 'JSON required.' });
    if (Number(req.headers['content-length']) > 16000) return res.status(413).json({ error: 'Message is too large.' });
    let body;
    try {
      const raw = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);
      if (!raw || Buffer.byteLength(raw) > 16000) return res.status(413).json({ error: 'Message is too large.' });
      body = validateMessage(JSON.parse(raw));
    } catch { return res.status(400).json({ error: 'Invalid message.' }); }
    if (!body) return res.status(400).json({ error: 'Please check your details and verification.' });
    try {
      const verification = await fetcher('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
        method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({ secret: settings.secret, response: body.token }), signal: AbortSignal.timeout(8000),
      });
      if (!verification.ok) return res.status(502).json({ error: 'Verification unavailable. Please try again.' });
      const verified = await verification.json();
      if (!verified.success || verified.hostname !== settings.hostname || verified.action !== 'contact') {
        return res.status(400).json({ error: 'Verification expired or failed. Please verify again.' });
      }
      const { html, text } = recruiterEmail(body);
      const idempotency = createHash('sha256').update(JSON.stringify([body.requestId, body.name, body.email, body.company, body.message])).digest('hex');
      const result = await fetcher('https://api.resend.com/emails', {
        method: 'POST', headers: { Authorization: `Bearer ${settings.key}`, 'Content-Type': 'application/json', 'Idempotency-Key': idempotency },
        body: JSON.stringify({ from: settings.from, to: [recipient], reply_to: body.email, subject: 'New portfolio enquiry', html, text }),
        signal: AbortSignal.timeout(8000),
      });
      if (!result.ok) return res.status(result.status === 429 ? 429 : 502).json({ error: 'Email service unavailable. Please try later or use the email link.' });
      const accepted = await result.json();
      if (!accepted.id) throw new Error('Provider did not acknowledge acceptance');
      return res.status(202).json({ accepted: true });
    } catch {
      // Do not log visitor messages, tokens, or provider responses containing private data.
      return res.status(502).json({ error: 'Delivery could not be confirmed. Please try again or use the email link.' });
    }
  };
}

export default createContactHandler();